### ISSUE TITLE
ETQ agent visiteur je contacte l'équipe afin de créer mon compte

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#135]
* Refs #87 

## User Story

En tant qu'agent visiteur souhaitant utiliser DiaLog, je contacte l'équipe afin de créer mon compte et/ou mon organisation

## Critères d'acceptation

* [ ] Depuis la page d'accueil, il est clairement possible d'envoyer un e-mail à l'équipe
* [x] Adresse e-mail : **TODO** quelle adresse utiliser ? Un `contact[@]dialog.beta.gouv.fr` ? E-mail pro de @MathieuFV ?

## Design

Parcours utilisateur (proposition @florimondmanca - À retravailler)

* L'utilisateur accède à https://dialog.beta.gouv.fr
* L'utilisateur voit sur la page qu'il faut envoyer un e-mail à l'équipe si on n'a pas encore de compte
* L'utilisateur envoie un e-mail à l'équipe
* L'équipe échange avec l'utilisateur en off (e-mails) pour valider la demande de création de compte
* L'équipe tech crée le compte et l'organisation le cas échéant
* L'équipe informe l'utilisateur de ses identifiants de façon sécurisée
* L'utilisateur peut se connecter

Maquette TODO

## Implémentation

* [ ] Modifier la page d'accueil

**Comment by mmarchois** [comment]
Peut-on considérer cette issue comme traitée ? Il est possible de contacter l'équipe via le formulaire de login.

**Comment by florimondmanca** [comment]
Sur la page d'accueil il y a un bouton "Nous contacter" qui pour l'instant n'a aucun effet

Est-ce qu'on le garde ? Si oui, quel comportement lui faire adopter ? J'imagine qu'on peut faire un mailto vers dialog[@]beta.gouv.fr, comme sur la page de login

**Comment by mmarchois** [comment]
Je vais faire un mailto
