### ISSUE TITLE
ETQ utilisateur je supprime une réglementation afin de...

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#138]
## User story

* ETQ utilisateur je supprime une réglementation afin de corriger une erreur ou ne pas diffuser aux GPS des réglementations obsolètes

## Critères d'acceptation

_(Must have)_

* [x] Il est possible de supprimer une réglementation
* [x] Une réglementation supprimée disparaît effectivement de la liste
* [x] Une réglementation supprimée n'a plus de page de détail
* [ ] Une confirmation apparaît à l'écran après la suppression

_(Nice to have - Plus tard)_

* Un message indique à l'utilisateur que la suppression est définitive (pas de "undo")
* Un message indique à l'utilisateur la conséquence du point de vue de la transmission aux GPS

## Design

_(À confirmer)_

* Bouton "Supprimer la réglementation" sur la page de détail
* Modale de confirmation avant de procéder à la suppression

## Implémentation

**Comment by astranchet** [comment]
Tant que les données ne sont pas intégrées dans les GPS, on peut faire un parcours super simple. Et éventuellement un parcours "idéal" en proto à montrer aux GPS pour donner une idée de comment on pourrait leur communiquer quand un truc change. 

Est-ce qu'on se lance direct dans les maquettes, ou mieux vaut faire un point design+dev avant ?
