### ISSUE TITLE
ETQ utilisateur je définis le type de véhicule afin de n'appliquer la restriction qu'à ce type

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#176]
## User story

ETQ utilisateur je définis le type de véhicule afin de n'appliquer la restriction qu'à ce type

## Critères d'acceptation

* [ ] _(Must have)_ Par défaut la restriction s'applique à tous les véhicules.
* [ ] _(Must have)_ Il est possible de n'appliquer la restriction qu'à certains véhicules
* [ ] _(Must have)_ Il est possible d'exempter certains véhicules de la restriction

## Design

Cf [Maquette](https://www.figma.com/file/YuT6Uh4wxe90U8LaPLlDzO/Dialog?type=design&node-id=6-2&t=IzrHavv1AOKD8maS-0)
