### ISSUE TITLE
ETQ compétence voirie, je déclare les emprises d'arrêté afin de localiser les mesures qui s'y appliquent

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#186]
* Fait partie de #185 

## User story

ETQ titulaire/délégataire de la compétence voirie, je déclare les emprises dans un arrêté afin de localiser les mesures qui s'y appliquent

## Critères d'acceptation

- [x] _(Must have)_ Dans un arrêté, il est possible de renseigner une ou plusieurs emprises (localisations sur lesquelles l'arrêté dispose de mesures)
- [x] _(Must have)_ Au moins une emprise doit être renseignée
- [x] _(Must have)_ On peut renseigner sur une emprise les informations suivantes : code postal, ville, nom de voie
- [x] _(Must have)_ L'emprise dispose des champs optionnels suivants : numéros de voie (permettent d'indiquer une section de rue plutôt qu'une rue complète) #240
- [x] _(Must have)_ L'utilisateur est assisté dans sa saisie de ville et de rue #213
- [x] _(Must have)_ Il est possible de supprimer une emprise #281
- [ ] _(Nice to have)_ ~À chaque emprise est assigné un numéro ou un tag permettant de la retrouver~

## Implémentation

* [x] Mise à jour du MCD #220
* [x] Refonte étape 2 "Localisation"

## Contexte supplémentaire

Exemples :

* Sur l'emprise "Rue rue B du numéro U au numéro V", qui a une plage de validité spécifique pour toutes les mesures définie par "Du lundi au vendredi"
  * La mesure "Poids lourds et véhicules transportant des matières dangereuses interdits à la circulation", sans plage de validité spécifique, s'applique du lundi au vendredi

**Comment by florimondmanca** [comment]
Tous les critères d'acceptation sont désormais remplis, je clos ce ticket
