### ISSUE TITLE
ETQ compétence voirie, je déclare les restrictions qui s'appliquent sur une localisation afin de les communiquer aux usagers et autres parties prenantes

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#187]
- Fait partie de #185

## User story

ETQ compétence voirie, je déclare les mesures et leur plage de validité sur une emprise afin de les communiquer aux usagers et aux autres parties prenantes (police de circulation, police municipale, services d’urgence, etc.)

## Critères d'acceptation

- [x] _(Must have)_ Pour chaque emprise, il est possible de définir une ou plusieurs mesures. Ce sont les règles qui s'appliquent sur cette emprise. Il est possible de les modifier une fois ajoutées. #313 
- [x] _(Must have)_ Il est possible de supprimer les mesures une fois ajoutées #327 
- [x] _(Must have)_ Au moins une mesure doit être renseignée. #326 
- [x] _(Must have)_ Une mesure peut être de l'un de ces types : circulation interdite, circulation alternée, circulation à sens unique, limitation de vitesse.
- [x] _(Must have)_ Par défaut, les mesures s'appliquent à tous les véhicules. _(Au moins dans cette première version adaptée aux besoins des communes et EPCI.)_
- [x] _(Must have)_ Il est possible de préciser à quels véhicules la mesure s'applique. https://github.com/MTES-MCT/dialog/issues/176
- [x] _(Must have)_ Par défaut, les mesures s'appliquent tous les jours entre le début et la fin de l'arrêté
- [x] _(Must have)_ Il est possible de préciser les créneaux horaires où la mesue s'applique : on peut en ajouter, modifier les créneaux existants, ou en supprimer. #346

## Design

cf [Figma](https://www.figma.com/file/YuT6Uh4wxe90U8LaPLlDzO/Dialog?node-id=6%3A2&t=vcijrgnlfBzzLCfa-1)

## Implémentation

* Les mesures sont intégrées au formulaire d'une localisation via un champ de type [`CollectionType`](https://symfony.com/doc/current/form/form_collections.html)
* Idem pour les créneaux horaires au sein d'une mesure

## Contexte supplémentaire

Exemples :

* Sur l'emprise "Rue A du numéro X au numéro Y", sans plage spécifique définie pour toutes les mesures, considérons deux mesures :
  * Une mesure "Poids lourds interdits à la circulation", qui a une plage de validité spécifique : le samedi et le dimanche.
  * Une mesure "Véhicules de plus de 3m de haut interdits à la circulation", sans plage de validité spécifique. Elle s'applique donc tout le temps.

**Comment by florimondmanca** [comment]
@MathieuFV J'ai partagé entre ici et #186 l'idée de pouvoir préciser une plage de validité plus précise au niveau de chaque mesure ou bien au niveau d'une emprise pour l'ensemble de ses mesures.

**Comment by florimondmanca** [comment]
@MathieuFV Idem que #186, j'ai recopié ici les informations de #215, qui était considéré comme "Validé" donc je passe ce ticket en "Validé" aussi.

**Comment by florimondmanca** [comment]
TODO @florimondmanca : regarder dans DATEX II comment est modélisée la notion de sens de circulation (pour les restrictions de circulation à sens unique)
