### ISSUE TITLE
ETQ compétence voirie, je modifie un arrêté afin de le garder à jour

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#188]
## User story

ETQ titulaire/délégataire de la compétence voirie, je modifie un arrêté afin de le garder à jour

## Critères d'acceptation

- [ ] _(Must have)_ La plage de validité globale de l'arrêté peut être modifiée
- [ ] _(Must have)_ Les emprises d'un arrêté peuvent être modifiées
- [ ] _(Must have)_ Les mesures d'une emprise peuvent être modifiées
- [ ] _(Must have)_ Un arrêté publié ne peut PAS être modifié. Il doit être en brouillon pour être modifié. (à discuter)
- [ ] _(Nice to have)_ La description de l'arrêté peut être modifiée

**Comment by aureliebaton** [comment]
Si l'objectif est de garder à jour un arrêté cela implique que cet arrêté est publié, donc le critère : "Un arrêté publié ne peut PAS être modifié. Il doit être en brouillon pour être modifié. (à discuter)" ne peut pas s'appliquer. 
Il faudrait peut être un mécanisme comme Rennes avait mentionné où un arrêté peut être abrogé automatiquement et remplacé quand on change la date.

**Comment by florimondmanca** [comment]
En effet ce critère (c'est moi qui l'avait ajouté pour discussion) implique de creuser la question de la "fin de vie" d'un arrêté : dans quelles situations un arrêté arrive en "fin de vie", et qu'est-ce que ça veut dire exactement ?

* Suppression pure et simple (pour cause d'erreur par exemple) : comment traiter ce cas ?
* Fin de validité d'un arrêté temporaire : l'arrêté passe-t-il dans un mode "archivé" / "passé" ?
* Abrogation : comment traiter ce cas d'usage métier ?

**Comment by johanricher** [comment]
Je ne comprends pas trop ce ticket puisqu'il est clairement explicité que "Un arrêté publié ne peut pas être modifié". Par conséquent seul un arrêté non publié, c'est à dire à l'état de brouillon, peut être modifié et c'est déjà le cas. Que manque-t-il ?

**Comment by florimondmanca** [comment]
Ce ticket semble dépassé... Aujourd'hui on peut tout modifier tant que l'arrêté est en brouillon, et on ne peut plus modifier une fois qu'il est publié. C'est en un sens conforme aux critères qui avaient été listés. D'ailleurs, ceux-ci avaient été listés unilatéralement par moi-même et pas vraiment discutés ni utilisés comme support de planification du travail...
