### ISSUE TITLE
ETQ délégataire de la compétence voirie, je transmets un arrêté au pouvoir de police de circulation afin de le valider

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#196]
## User story

ETQ délégataire de la compétence voirie, je transmets les mesures à publier au pouvoir de police de circulation afin qu'il valide leur publication

## Critères d'acceptation

- [ ] _(Must have)_ A la fin du formulaire de renseignement de l'arrêté apparaît l'option "publier" assortie de la précision "suite à validation par l'autorité chargée du pouvoir de police de circulation"
- [ ] _(Nice to have)_ Apparition d'une fenêtre pop-up contenant les mesures qui sont transmises pour publication avec un rappel (êtes vous sûr...) (à discuter)
- [ ] _(Must have)_ Un arrêté brouillon transmis pour validation reste modifiable jusqu'à validation

**Comment by florimondmanca** [comment]
@MathieuFV J'ai l'impression que les critères d'acceptation sont un peu trop orientés "solutions de design"

Par exemple :

> A la fin du formulaire de renseignement de l'arrêté apparaît l'option "publier" assortie de la précision "suite à validation par l'autorité chargée du pouvoir de police de circulation"

Ici "l'option 'publier'" fait penser aux boutons existants "Sauvegarder en brouillon" / "Publier", ce qui est une implémentation design.

Je reformulerais en : "Dans la page d'édition de l'arrêté, il est possible de transmettre l'arrêté à l'autorité détentrice du pouvoir de police de circulation sur mon organisation."

Je pense qu'il faut imaginer le parcours utilisateur plus complet de cette "transmission pour validation". En effet, ce critère nous amène à se demander : Que se passe-t-il une fois qu'on a "transmis pour validation" ?

Par exemple :

* Qu'est-ce qui change à l'écran ? Le fait que c'est "en cours de validation" doit-il apparaître quelque part ? (Dans la section "Design" on s'intéressera alors à où et comment)
* Peut-on "annuler une transmission pour validation" ?
* Peut-on "envoyer un rappel" ?
* Doit-on faire apparaître les contacts (ex : identité, adresse e-mail) d'utilisateurs détenteurs du pouvoir de police de circulation pour cette organisation, afin de faciliter une prise de contact autonome ?

> Apparition d'une fenêtre pop-up contenant les mesures qui sont transmises pour publication avec un rappel (êtes vous sûr...) (à discuter)

Ici "fenêtre pop-up" est également une considération trop orientée "solution de design".

Un critère d'acceptation plus fonctionnel serait : "Une confirmation est demandée avant la transmission pour publication". Ainsi que : "Les mesures sont rappelées à l'écran lors de la confirmation avant transmission pur publication"

**Comment by johanricher** [comment]
On ferme ce ticket pour l'instant en attendant d'avancer sur l'exploration de #183
