### ISSUE TITLE
Export d'un arrêté

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#199]
## User story

ETQ agent qui a la responsabilité des arrêtés de circulation dans mon organisation,
j'ai besoin d'exporter les informations que j'ai saisies dans DiaLog concernant un arrêté,
afin de pouvoir les recopier dans l'outil utilisé pour finaliser l'arrêté.

ETQ élu,
j'ai besoin que les informations saisies pour un arrêté dans DiaLog soient conformes à celles de l'arrêté publié,
afin de ne pas exposer mon administration à un risque juridique.

## Critères d'acceptation

- [x] _(Must have)_  Dans DiaLog, depuis la page de détail d'un arrêté déjà publié, je peux exporter l'arrêté au format `.docx`
- [x] _(Must have)_  Le document exporté contient toutes les informations sur les restrictions de circulation, et de façon à faciliter les adaptations nécessaires à la publication de l'arrêté
- [x] _(Must have)_ Les personnes qui ouvrent le document exporté comprennent que le contenu qui porte sur les restrictions de circulation (tout ce qui est dans le périmètre des données exposées par l'API de DiaLog) ne doit pas être modifié

## Design

* Interface de Dialog (bouton sur la page d'un arrêté publié) : [maquette](https://www.figma.com/file/YuT6Uh4wxe90U8LaPLlDzO/Dialog?type=design&node-id=1526-102564&mode=design&t=oBnegXrkjkXVE4jL-4)
  * Pour l'instant on ne met pas le poids du fichier (néanmoins cette information est [considérée comme obligatoire dans le DSFR](https://www.systeme-de-design.gouv.fr/elements-d-interface/composants/telechargement-de-fichier/))
* Document exporté : [trame](https://kdrive.infomaniak.com/app/office/184671/26456)
  * La mise en forme actuelle de cette trame est indicative, le plus important sont les must have
  * Les différents textes peuvent encore être modifiés et doivent être finalisés avant la cloture du ticket notamment la partie "information importante"

[Travaux basés notamment sur les templates publiés par le département de Haute-Saone](https://www.haute-saone.gouv.fr/Actions-de-l-Etat/Amenagement-du-territoire-construction-logement/Appui-aux-collectivites-locales/Documents-a-l-intention-des-Maires/Gestion-de-la-voirie-communale-arretes-de-circulation)

## Implémentation

* [ ] #402
