### ISSUE TITLE
ETQ compétence voirie, je souhaite pouvoir entrer une adresse avec de l'aide à la saisie afin de limiter les erreurs

### ISSUE THREAD

**Issue by mmarchois** [MTES-MCT/dialog#213]
## User story

En tant que compétence voirie, je souhaite pouvoir saisir une localisation avec de l'aide à la saisie afin de limiter les erreurs de saisie

## Critères d'acceptation

- [ ] _(Must have)_ Toggle "toute la commune"
- [ ] _(Must have)_  Champs adresse (ville + voie) en autocomplete.

## Design

TODO par @aureliebaton ou @astranchet pour maquetter (notamment le toggle)

## Implémentation

Spécification du champ d'adresse en autocomplete : 
- Si j'ai coché "toute la commune", je dois utiliser le type "commune" de l'api adresse
- Si je n'ai pas coché "toute la commune", je dois utiliser le type "rue" de l'api adresse

* [x] Endpoint d'API servant de proxy avec l'API Adresse
* [x] Adapter le formulaire : un seul champ "adresse"
* [ ] Ajouter l'autocomplétion sur le champ adresse #255

### Solution technique d'autocomplétion

Réutiliser le code de [stimulus-autocomplete](https://github.com/afcapel/stimulus-autocomplete) directement dans le repo, en l'adaptant au besoin

Notamment:

* On pourra adapter les styles pour utiliser ceux du DSFR (le code utilise bootstrap par défaut)
* D'après https://github.com/afcapel/stimulus-autocomplete/issues/120 qui renvoie vers https://www.w3.org/WAI/ARIA/apg/patterns/combobox/examples/combobox-autocomplete-list/#rps_label il y aura quelques ajustements d'accessibilité à faire (éventuellement à contribuer en retour par la suite)

Inspirations

* [Exemple accessible gov.uk](https://alphagov.github.io/accessible-autocomplete/examples/)

Solutions rejetées

* Symfony a un bundle [symfony/ux-autocomplete](https://symfony.com/bundles/ux-autocomplete/current/index.html#extending-tom-select). Mais il semble y avoir des styles inclus et un comportement plutôt "multiselect autocomplete" par défaut (plutôt qu'un autocomplete sur un `<input />`, bien que ça semble possible)

## Contexte supplémentaire

https://adresse.data.gouv.fr/api-doc/adresse

**Comment by mmarchois** [comment]
cf https://github.com/MTES-MCT/dialog/issues/175

**Comment by florimondmanca** [comment]
Proposition d'UX et réalisation basée sur un seul champ

Voir : https://pad.incubateur.net/5lDle3AERgiosMbDQyRMnA?both#2023-04-03---D%C3%A9veloppement-autocompl%C3%A9tion

* L’adresse est stockée en BDD comme un pur champ texte
* L’API Adresse sert de source de vérité
* Pré-remplissage à partir de CP/ville paramétré dans l’organisation : on les passe en paramètres postcode et/ou city à l’API Adresse, qui ne renvoie que les rues correspondantes. (Et a priori pas possible de trouver des adresses en dehors de la ville.)
* Interaction avec “Toute la ville” : si coché, on utilise la valeur du champ adresse (dont rue, ville, CP) pour requêter l’API Adresse avec type: municipality.
* Rues communes : le problème ne se pose pas si la ville est pré-paramétrée au niveau de l’organisation. Et pas un problème de toute façon pour un EPCI, qui doit avoir accès à diverses villes.

Niveau archi on continuerait de faire office de proxy entre le navigateur

![Diagramme sans nom drawio](https://user-images.githubusercontent.com/15911462/229472344-371b438f-205d-4dd0-97e0-0cdd431cf445.png)

**Comment by florimondmanca** [comment]
@aureliebaton @astranchet Voici un aperçu de ce que ça donnerait

![Screenshot 2023-04-04 at 11-23-32 Étape 2 sur 4 - DiaLog](https://user-images.githubusercontent.com/15911462/229748122-12c5d7bb-64b3-4630-a98a-585f207acd6d.png)

**Comment by florimondmanca** [comment]
@aureliebaton Oui, on va prendre ça en compte
