### ISSUE TITLE
ETQ compétence voirie, je rédige un arrêté complet dans DiaLog afin de gérer dans un seul outil la réglementation dont j'ai la responsabilité

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#215]
## User story

ETQ compétence voirie, je renseigne un arrêté contenant plusieurs emprises, contenant elles-mêmes plusieurs mesures afin de pouvoir rédiger un arrêté complet dans DiaLog

## Critères d'acceptation

- [x] _(Must have)_ L'utilisateur ne renseigne plus de "réglementation" mais des "arrêtés"
- [x] _(Must have)_ Un arrêté a obligatoirement : organisation compétente, nom, date d'entrée en vigueur
- [x] _(Must have)_ Un arrêté peut avoir : une plage de validité. Si elle est définie, on dit que l'arrêté est temporaire. Sinon (seulement une date d'entrée en vigueur), l'arrêté est permanent.
- [x] _(Must have)_ Un arrêté contient des emprises. Il s'agit des différentes localisations où l'arrêté prévoit des mesures applicables. Voir : #186
- [x] _(Must have)_ Une emprise contient des mesures. Ces mesurs sont les règles qui s'appliquent sur l'emprise concernée. Voir : #187

## Design

Cette user story demande à refondre les formulaires et interfaces en prenant en compte les critères d'acceptation ci-dessus

## Implémentation

Cette user story demande à refondre le modèle de données et ce qui en dépend

Pour les informations générales de l'arrêté:

* [x] Date de début et de fin optionnelles #218 
* [x] Utiliser `startDate/endDate` dans le reste de l'interface au lieu de `OverallPeriod`
* [x] Supprimer `OverallPeriod` https://github.com/MTES-MCT/dialog/pull/231

## Contexte supplémentaire

**Exemple d'usage :** 

Dans un arrêté en vigueur du 15 au 20 mars 2023, je définis deux emprises : 

- Entre le 1 et le 25 de la rue Duval (Emprise 1)
- du 13 au 25 de la rue Tintinmarre (Emprise 2)

Dans ces emprises, je suis capable : 

Pour l'emprise 1 : 
- D'interdire la circulation aux poids lourds SAUF livraison chantier DU lundi AU vendredi ENTRE 8h et 12h SAUF jours fériés (Mesure 1)
- D'appliquer une circulation alternée pour tous les véhicules TOUS LES JOURS (Mesure 2)

Pour l'emprise 2:
- D'appliquer une une circulation à sens unique dans le sens des numéros croissants pour les tous les véhicules TOUS LES JOURS (Mesure 1)

**Comment by florimondmanca** [comment]
@MathieuFV Je me suis permis de transformer ce ticket en quasi-epic pointant vers les autres user stories : emprises, mesures

En effet, sinon il faisait doublon avec lesdits autres tickets

À ce titre je viens de proposer une reformulation de la user story:

> ETQ compétence voirie, je rédige un arrêté complet dans DiaLog afin d'y gérer la réglementation dont j'ai la responsabilité

**Comment by MathieuFV** [comment]
Je pensais ajouter à ce ticket la gestion des motifs (considérant...) et des annexes (Vu le code...). Qu'en pensez-vous ?

Pour l'implémentation de ces deux nouveaux champs, le minimum (must have) semble être un champ texte à placer dans le workflow de rédaction d'un arrêté (on peut regarder dans Eudonet et Sogelink à quel moment ça arrive), et on peut aussi penser à des nice to have : 

Pour les motifs, on peut supposer que l'information du motif est aussi intéressante pour les utilisateurs finaux, par exemple un GPS pourrait faire apparaître une option pour les montrer dans une infobulle aux utilisateurs curieux, ou aux entreprises. Dans ce cas là on peut imaginer qu'il serait utile que chaque motif soit séparé des autres plutôt que mélangé dans un unique bloc de texte (à discuter).

Pour les annexes c'est encore plus vaste, les annexes sont toujours piochées dans des textes de loi, des codes ou des textes réglementaires (décrets ou autres arrêtés). Ce sont elles qui donnent une assise juridique à la décision du maire quand il arrête une mesure. Suivant le type de mesure prise par le maire, les annexes peuvent changer. Dans la pratique on retrouve donc "souvent" les mêmes annexes d'un arrêté à un autre mais pas toujours. On pourrait imaginer pour faciliter la vie de l'opérateur qu'il puisse aller piocher dans une bibliothèque d'annexes qu'il utilise couramment, ou bien qu'il puisse chercher une annexe parmi des textes courants (code de la voirie routière, code général des collectivités territoriales, code de la route, code pénal, etc.). Il y a pour nous aider une API de Légifrance qui permet d'explorer l'ensemble des textes publiés et à jour (https://developer.aife.economie.gouv.fr/index.php?option=com_apiportal&view=apitester&usage=api&apitab=tests&apiName=L%C3%A9gifrance&apiId=3a3d114a-b046-4f88-8890-b2b4573381e3&managerId=2&type=rest&apiVersion=1.8.4&Itemid=265&swaggerVersion=2.0&lang=fr)

A votre disposition pour en parler!

**Comment by florimondmanca** [comment]
@MathieuFV 

> PS : Vu le commentaire précédent de Florimond, on peut créer un nouveau ticket et faire pointer cette issue dessus

Oui :+1: On peut créer un nouveau ticket qu'on listera dans ce ticket d'epic

Il semble qu'on peut même créer 2 tickets, à savoir traiter les motifs et les annexes comme deux tickets séparés ? Sauf erreur, implémenter l'un n'empêche pas d'implémenter l'autre.

## Dans Eudonet

### Motifs

Ce sont des fiches contenant un texte libre. Ils sont liés à la fiche arrêté.

### Annexes ("Visas")

Dans Eudonet, les annexes sont appelés "Visas". Les "annexes" pour Eudonet sont des fichiers joints (PDF, Word).

Il y a :

**Visas** : 

* Ça semble correspondre aux annexes légales généralement invoqué pour tel ou tel type de mesure
* Constitué d'un type de mesure (ex : circulation interdite), d'une liste (text libre) d'articles du CGCT (Code général des collectivités territoriales) et d'une liste (texte libre) d'articles du Code de la route
* Exemple : Mesure = "135 - circulation interdite", article CGCT = "L. 2213-1 ; L. 2213-2 ; L. 2512-14", article du code de la route = "R. 411-25 ; R. 411-8"
* Ça pourrait faire office de "bibliothèque", sauf que les visas ne sont pas directement reliés à d'autres fiches. Par conséquent je ne suis pas sûr de comment ils sont utilisés par le système Eudonet. Ajout automatique lors de la génération en fonction des mesures en présence ? À clarifier.
* Il semble y avoir beaucoup de quasi-duplication. Les visas d'un même type de mesure ont souvent les mêmes articles, mais pas toujours. J'imagine que cela correspond à des changements dans la loi : il faut référencer tel ou tel article en plus. Le visa le plus ancien dte de 2017, le plus récent date de 2021. 

**Visas complémentaires** :
* Reliés à un arrêté
* Ce sont des "Vu" spécifiques à un contexte, par exemple "Vu la délibération du conseil municipal de telle date..."

**Comment by MathieuFV** [comment]
Ok je crée les tickets correspondants, je trouve bien la distinction entre visas et visas complémentaires, qu'on peut garder dans notre implémentation (à discuter de manière plus approfondie sur l'issue).

**Comment by florimondmanca** [comment]
Je ferme ce ticket car tous les "critères d'acceptation" sont désormais cochés

À mon sens, on pourra toujours créer de nouveaux tickets pour ce qui nous semblera manquer à un "arrêté complet"
