### ISSUE TITLE
[Suivi] Améliorations suite à 1ère implem nouveau formulaire

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#269]
Repris de #260 

* [x] Remettre la possibilité de publier #271
  * [x] (UX) Activer le bouton "Publier" quand une localisation est créée
* [x] Renommer `SaveRegulationCommand` en `SaveGeneralInfoCommand` #280
* [ ] Désactiver les champs de numéros de rue si on détecte une ville entière #266 
* [x] Requêtes spécifiques pour récupérer la GeneralInfo et une Location #283 
* [x] Brancher le bouton "Dupliquer" sur la page de détail
* [x] Responsive : afficher la barre latérale en-dessous pour petits écrans -> #264
* [x] Titre arrêté permanent / temporaire en fonction de endDate
* [ ] Ajouter la barre latérale dans la page de création aussi
* [x] Bloc "Informations générales" : utiliser la description comme titre du bloc, avec limitation du nombre de caractères (troncature avec "...") #321
