### ISSUE TITLE
En tant que contributeur j’ajoute une réglementation de circulation à DiaLog afin qu’elle soit communiquée aux GPS

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#41]
Proposition de solution technique _absolument minimale_

**Prérequis**

* [x] #51 
* [x] #52

**Critères d'acceptation**

(Propositions @florimondmanca)

* Indispensable (_must-have_) :
  * [x] Un formulaire permet d'ajouter une réglementation
  * [x] La réglementation ajoutée s'affiche sous forme de liste
* Agréable (_nice-to-have_) :
  * [x] Il est possible de supprimer une réglementation de la liste
* Hors-champs:
  * La visualisation de l'ensemble des données arrêtés dans une page HTML n'est pas nécessaire
  * Pas de sécurisation particulière dans le cadre de ce ticket, c'est à traiter via #35
  * Pas de branchement sur l'endpoint XML dans le cadre de ce ticket, cela sera traité via #48

**UI**

* Page d'accueil : formulaire
* Page d'accueil : liste basique des arrêtés ajoutés : description + bouton "supprimer"
* Style : DSFR #51

**Implémentation**

* [x] Créer le formulaire en utilisant les commandes et requêtes #62 
* [ ] Implémenter les différents champs (à définir)
* [ ] https://github.com/MTES-MCT/dialog/issues/83
* [x] #96

**Comment by florimondmanca** [comment]
Proposition de solution technique _absolument minimale_

**Critères d'acceptation**

* Must have:
  * [ ] Un formulaire permet d'ajouter une réglementation
* Nice to have:
  * [ ] La réglementation ajoutée s'affiche sous forme de liste basique
  * [ ] Il est possible de supprimer une réglementation de la liste
* Hors-champs:
  * La visualisation de l'ensemble des données arrêtés dans une page HTML n'est pas nécessaire
  * Pas de sécurisation particulière à ce stade (cf #35)
  * Pas de branchement sur l'endpoint XML dans le cadre de ce ticket, cela sera traité via #48

**UI**

* Page d'accueil : formulaire
* Page d'accueil : liste basique des arrêtés ajoutés : description + bouton "supprimer"
* Style : HTML brut ou CSS minimal (aucun effort de développement à faire de ce côté-ci pour l'instant)

**Implémentation**

* [ ] Créer le formulaire, ainsi que la commande, le handler, et le repository associés.
* [ ] Branchement de la donnée dans l'endpoint XML, cf #48
* [ ] Styling basique : raw HTML ou librairie CSS classless type [missing.css](https://missing.style) ou [pico.css](https://picocss.com/).

**Comment by astranchet** [comment]
@florimondmanca Pour le styling basique, je propose quand même de commencer direct avec le DSFR. Ça ne sera pas beaucoup plus complexe et ça sera utile par la suite. On peut en reparler demain.

**Comment by florimondmanca** [comment]
@astranchet Je n'y avais pas pensé mais en effet ! Cela dit, l'intégration du DSFR pourrait être une issue à part. On pourrait prendre le site "vide" ("Bienvenue sur DiaLog") actuel et le porter sur le DSFR. Ça demande de définir un certain nb de choses, notamment le contenu du header.

**Comment by mmarchois** [comment]
Cette issue peut être close ?

**Comment by florimondmanca** [comment]
C'est une question de PO / gestion de backlog.

> "Est-ce qu'on considère qu'on a pour l'instant "tout ce qu'il faut" pour ajouter une réglementation de circulation ?"

Personnellement je dirais que oui "dans une version minimale". En effet, la vignette Crit'air n'a pas l'air d'être un point majeur ; récemment on n'en n'a pas vraiment parlé.
