### ISSUE TITLE
Gestion des intersections

### ISSUE THREAD

**Issue by johanricher** [MTES-MCT/dialog#419]
## Contexte

De nombreux arrêtés de circulation indiquent des localisations spécifiées par des intersections de voies (routes, rues...).

Actuellement, [la solution de géocodage implémentée pour DiaLog](https://github.com/MTES-MCT/dialog/blob/main/docs/adr/005_geocoding.md) (l'API Adresse) ne permet de pas de gérer les intersections, c'est à dire de transformer des intersections rédigées dans un langage lisible par un humain en coordonnées géographiques lisible par une machine.

Une solution permettant à DiaLog de gérer les intersections doit être trouvée pour traiter un plus grand nombre d'arrêtés et de cas d'usage (notamment #343).

## Exemples d'intersections

Il existe un nombre significatif d'intersections différentes, avec des problématiques spécifiques à gérer, selon les types de voies de la BD TOPO et les combinaisons entre elles :

* [x] Intersection entre deux voies nommées
  * Cas d'usage création de données avec Dialog #726
  * Cas d'usage intégration de données dans DiaLog (déjà géré pour Eudonet cf. #343 #533)
* [ ] Intersection entre deux routes départementales (nécessite #571)
* [ ] Intersection entre une voie nommée et une route départementale
* etc.

Travaux à prioriser en fonction de l'intérêt pour DiaLog (volumétrie de données à intégrer, nombre de collectivités demandeuses) et de la complexité.

## Critères d'acceptation

A définir au cas par cas (chaque type d'intersection ayant potentiellement des problématiques spécifiques à gérer, cf. exemples ci-dessus).

## Implémentation

Une exploration préalable à toute implémentation doit d'abord être menée.

L'API Adresse actuellement utilisée par DiaLog implémente le logiciel libre [Addok](https://github.com/addok/addok) pour son géocodage, avec les données de la BAN. Cette implémentation est limitée puisque la BAN ne contient que des points (adresses), sans les linéaires des voiries. Ces derniers sont notamment nécessaires pour générer les points des intersections, qui peuvent à leur tour être indexés dans Addok.

[L'instance de démo d'Addok](https://demo.addok.xyz/) permet de tester ce fonctionnement, avec des intersections qui ont été indexées sous forme de "poi" (points of interest)  :
* [Endpoint de recherche avec l'API](https://demo.addok.xyz/search) ([doc](https://addok.readthedocs.io/en/latest/api/#search))
* Données extraites d'OSM
* [Exemple de script](https://gist.github.com/cquest/c0a84e6757d15e66e6ae429e91a74a9e) (Ile-de-France uniquement)
* [Discussion](https://teamopendata.org/t/2165/7) pour une application à un cas pratique

L'API Adresse est basée sur la Base d'adresse nationale (BAN) pas sur les données OSM. Les deux bases ont des différences à ne pas négliger (notamment points seulement pour la première vs points, linéaires et polygones pour la deuxième), avec des implications à vérifier par rapport à nos cas d'usages.

Une instance Addok spécifique à DiaLog serait une infrastructure relativement lourde donc coûteuse à maintenir, qui n'est pas la vocation primaire de la startup d'Etat. On ne devrait l'intégrer au périmètre de DiaLog que si aucune alternative ne répondant à nos besoins ne peut être trouvée.

L'exploration pourrait être menée en discutant avec les personnes compétences en la matière, notamment celles présentes sur le salon [~etalab-geo](https://mattermost.incubateur.net/betagouv/channels/etalab-geo), et avec des services développés au sein de beta qui pourraient avoir les mêmes besoins que nous.

### Questions

L'exploration doit notamment permettre de répondre à ces questions :
* Est-ce que des [géocodeurs alternatifs à l'API Adresse](https://guides.etalab.gouv.fr/apis-geo/1-api-adresse.html#geocodeurs-alternatifs), disponibles sous forme de service (API) gratuit, répondent à nos besoins ?
* Est-ce que d'autres équipes beta.gouv.fr ont un besoin similaire au nôtre ? (pourrait donner lieu à une mutualisation au niveau de Beta si elle n'existe pas encore)
* Est-ce qu'on peut déployer une instance Addok qui mélange des données de la BAN et celles d'OSM (pour les intersections et les POIs) ? #439

**Comment by MathieuFV** [comment]
Comme convenu un exemple d'arrêté qui utilise les croisements de rues pour définir les tronçons concernés : 

[V2 Arrete SDF.pdf](https://github.com/MTES-MCT/dialog/files/12161813/V2.Arrete.SDF.pdf)

**Comment by johanricher** [comment]
Merci ! j'ai ajouté l'exemple sur le ticket. Est-ce que tu aurais d'autres exemple d'arrêtés avec des intersections ? par exemple quelque chose qui ressemblerait à "entre le croisement de l'avenue X et de la rue Y et le croisement de l'avenue X et la rue Z" voire d'autres formulations encore plus complexes (plus on aura d'exemple divers mais représentatifs, mieux ça sera).

**Comment by MathieuFV** [comment]
Je vais en trouver d'autres, j'ai toute une base de données (en PDF)!

**Comment by johanricher** [comment]
> Supposer que DiaLog doive géocoder les intersections (...) c'est faire l'hypothèse que les GPS ne seraient pas capables de traiter de la donnée textuelle.

Pour moi c'est plutôt faire l'hypothèse que les géocodages opérés par les différents fournisseurs services de navigation n'arriveront pas tous au même résultat, ce qu'on veut évidemment éviter ! Or, le géocodage de Google Maps et celui de l'API Adresse n'arrivent pas toujours au même résultat par exemple, notamment car les données utilisées diffèrent. En l'absence de données sur les adresses, Google (et certainement d'autres) a eu tendance à inventer leur géocodage en extrapolant sur la longueur de la rue. En France seule la BAN (qui commence à être utilisée par Google Maps mais sans qu'on puisse vraiment le vérifier) fait référence pour les adresses et fournit la seule source de vérité pour le géocodage.

Faire nous même le géocodage des adresses saisies dans DiaLog, et diffuser aux GPS une coordonnée géographique précise au lieu d'une adresse textuelle telle qu'un humain l'écrirait, a pour effet :
1) de vérifier que l'adresse saisie existe bien et correspond bien à la localisation que l'utilisateur souhaite
2) de s'assurer que les données seront utilisées de la même façon par tous les GPS et donc que les usagers ne verront pas des restrictions de circulation avec des localisations différentes d'un GPS à l'autre

**Comment by florimondmanca** [comment]
@johanricher Très bons points :)

**Comment by MathieuFV** [comment]
Concernant le commentaire de @florimondmanca (pour être sûr de bien comprendre le fonctionnement de DiaLog...) : 

Je comprends que la représentation dans DATEX d'une section de route est réalisée à l'aide de trois paramètres : 

- Le doublet (X,Y) des points de départ et d'arrivée du tronçon,
- Le `roadname` qui désigne l'entité linéaire (dans son entièreté) sur laquelle s'appliquent les données.

Une question par rapport à ce dernier paramètre : comment est-on surs que le `roadname` que nous fournissons a un pendant dans les référentiels des réutilisateurs de la donnée ? Comment sait-on donc que `Avenue des Fruitiers, 93210 Saint-Denis` existe dans le référentiel routier de GMaps / TomTom / Here / Apple, etc. ?

S'agissant de la remarque de @johanricher : Effectivement je suppose que fournir systématiquement le point de données permettra de lever certaines ambigüités, dans le cas notamment où une autorité jugerait inexacte la manière dont un GPS afficherait les données.

**Comment by florimondmanca** [comment]
@MathieuFV 

> Le doublet (X,Y) des points de départ et d'arrivée du tronçon,

Il est obligatoire de donner une représentation des points de début et de fin de la section de route, mais ça peut prendre d'autres formes que des coordonnées latitude / longitude. Dans l'exemple ci-dessus ça prend la forme de "références textuelles".

> comment est-on surs que le roadname que nous fournissons a un pendant dans les référentiels des réutilisateurs de la donnée ? Comment sait-on donc que Avenue des Fruitiers, 93210 Saint-Denis existe dans le référentiel routier de GMaps / TomTom / Here / Apple, etc. ?

Dans DATEX II on peut adjoindre à `roadName` deux autres propriétés, `linearElementReferenceModel` et `linearElementReferenceModelVersion`, qui permettent d'identifier un "_road network reference model which segments the road network according to specific business rules_".

Je ne pense pas que l'API Adresse puisse faire office de "_road network reference model_". Ça correspondrait plutôt à la BD TOPO je pense ?

Ce serait une indication de là où les GPS devraient aller chercher pour obtenir l'élément vectoriel correspondant à la route indiquée par `roadName`.

On peut aussi prendre un autre chemin, et préciser la (poly)ligne qui décrit la route (une suite de coordonnées latitude / longitude), grâce aux propriétés `startPointOfLinearElement`, `intermediatePointOfLinearElement`, et `endPointOfLinearElement` (qu'on avait mal utilisés jusqu'ici).

**Comment by florimondmanca** [comment]
Je m'occupe de la prospection d'infos sur ~etalab-geo

**Comment by johanricher** [comment]
> Dans DATEX II on peut adjoindre à `roadName` deux autres propriétés, `linearElementReferenceModel` et `linearElementReferenceModelVersion`, qui permettent d'identifier un "_road network reference model which segments the road network according to specific business rules_".
> 
> Je ne pense pas que l'API Adresse puisse faire office de "_road network reference model_". Ça correspondrait plutôt à la BD TOPO je pense ?

J'ai un doute sur le fait que le "road network reference model" signifie la base de données d'où proviennent les informations sur la voirie (`roadName`) référencée  (en l'occurence pour nous ce serait plutôt la BAN que la BD Topo, voire potentiellement bientôt les [données du réseau routier national](https://www.data.gouv.fr/fr/datasets/bornage-du-reseau-routier-national/)). Il est question d'un "modèle de référence" plutôt que d'une "base de données de référence". [Sur cette page](https://docs.datex2.eu/general/DATEXII-UserGuide-LocationReferencing.html) il est question de "modèles" tels que ALERT-C, GML, TPEG, OpenLR...
Quoi qu'il en soit je ne pense pas utile de rentrer à ce point dans les arcanes de Datex. :)

> Comment sait-on donc que Avenue des Fruitiers, 93210 Saint-Denis existe dans le référentiel routier de GMaps / TomTom / Here / Apple, etc. ?

Pour moi on ne le sait justement pas. Une voie nouvellement créée (ou renommée) qui apparaît dans la BAN, et donc dans DiaLog via l'API Adresse, pourrait ne pas être présente tout de suite dans la base de données d'un autre GPS. C'est le but de la BAN de diffuser ça, mais on n'a pas de visibilité sur l'intégration de ces données dans les GPS. Néanmoins je ne pense pas que le cas où ce cas poserait souvent problème et je pense que ça deviendra de moins en moins probable avec la généralisation de la BAN comme seule base de référence pour les adresses.

> Ce serait une indication de là où les GPS devraient aller chercher pour obtenir l'élément vectoriel correspondant à la route indiquée par `roadName`.

Les GPS ne cherchent un élément que dans leur propre base. Le géocodeur de Google Maps utilise la base de données Google Maps, etc. Indiquer que notre source est la BAN ne garantira pas qu'un GPS fera du géocodage qui aura toujours un résultat égal au nôtre. La seule solution de garantir que tous les usagers verront la même localisation d'un GPS à l'autre est de fournir aux différents GPS directement des coordonnées géographiques (sans oublier la projection utilisée).

**Comment by florimondmanca** [comment]
Une autre source (novembre 2020) sur l'intégration (expérimentale ?) de données d'intersection issues d'OSM dans Addok / demo.addok.xyz (je ne sais pas si elles ont été intégrées au code source ou seulement "en live" sur cette instance de demo) : https://georezo.net/forum/viewtopic.php?pid=337396

**Comment by MathieuFV** [comment]
J'ai déjà échangé par le passé avec Christian Quest au sujet de DiaLog, c'était juste après la phase d'investigation (https://georezo.net/forum/viewtopic.php?id=127895). Il semble sensible au sujet des données de réglementation, si vous le souhaitez on peut le solliciter pour en savoir plus sur ce qu'est devenue cette démo ?

**Comment by florimondmanca** [comment]
cquest a aussi été cité / notifié en réponse à ma question sur ~incubateur-ops. Ça serait sympa de pouvoir discuter avec lui, si c'est lui la "source primaire" de ces données intersection et de ce qu'elles sont devenues ? :-)

Olivier Delteil vient de me répondre sur ~startup-adresse que l'ajout des intersections n'est "pas prévu dans les évolutions de l'API Adresse" car ça sort du cadre "adresses et numéros". Il indique que des SDIS (services départementaux incendies et secours) les traiteraient "pour leurs besoins propres". Il y aurait donc pourtant un besoin autre que le nôtre à faciliter leur accès. J'ai demandé si les SDIS repartaient d'Addok, j'éditerai quand j'aurai une réponse.

**Comment by florimondmanca** [comment]
Hello!

J'essaie de faire un bilan des différentes options qui se présentent à nous jusqu'ici.

@johanricher Je 

### API Adresse seule (status quo)

Statut : :x: insuffisant

Cette option n'est pas suffisante car l'API Adresse ne gère pas les intersections, seulement "des rues avec des points adresses".

### Instance Addok avec intersections OSM

Statut : :thinking: POC concluant (#439), des questions subsistent

Dans #439 j'ai réussi à intégrer les intersections d'Ile-de-France à partir des données OpenStreetMap (OSM) récupérées sur [Geofabrik](https://download.geofabrik.de/europe/france/ile-de-france.html).

Le principe serait alors de déployer notre propre instance Addok avec les données BAN + ces données d'intersection. Cela revient à avoir notre instance de l'API Adresse augmentée avec les données d'intersection.

Ce qu'a montré le POC, c'est que déployer une instance répliquant l'API Adresse est plutôt facile, grâce au [setup Docker](https://github.com/BaseAdresseNationale/addok-docker) de Jérôme Desboeuf.

Des questions et problèmes subsistent :

* Les données OSM ne sont pas iso-BAN, ce qui pourrait créer (créera) des problèmes de compatibilité.
* La charge de déploiement et de maintenance d'une telle instance est à clarifier
  * Comment déployer effectivement cette instance ? Packager une image Docker et la déployer sur Scalingo avec un [custom buildpack] ?
  * Quelle procédure pour mettre à jour les données ? Il nous faudrait un repo séparé pour "builder" l'image et en publier de nouvelles versions.
* Les données France entière sur Geofabrik ne sont pas disponibles en format SHP. Seul PBF est dispo. Je n'ai pas encore regardé si l'outillage géographique (gdal) permettait de traiter ce format.

### Instance Addok avec intersections BDTOPO

Statut : :question: à explorer

Cette option est similaire à l'option Addok + OSM, mais on utiliserait la BDTOPO pour calculer les intersections.

Il est _possible_ que les intersections figurent déjà dans la BDTOPO sous forme de POI. Contrairement à l'option OSM, on n'aurait donc pas d'étape de calcul, ni d'étape de normalisation avec récupération des codes postaux (pourvu que la BDTOPO n'inclue pas que le code Insee).

Il "suffirait" d'exporter les intersections au format JSON compréhensible par Addok et de les y importer.

Questions en suspens

* Où sont les données d'intersection dans la BDTOPO ?
  * S'ils sont dans le [thème "Transport"](https://geoservices.ign.fr/bdtopo#telechargementtransportter), le fichier fait 3,6 Go, il reste envisageable de développer avec localement.
  * S'il est autre part dans la BDTOPO, il faut la récupérer en entier puis ne garder que la partie qui nous intéresse. Or la BDTOPO entière est volumineuse. La [page de téléchargement](https://geoservices.ign.fr/ressource/219590) indique 30 Go de données _compressées_ réparties en 8 fichiers. Voir [tuto import PostgreSQL](https://geoservices.ign.fr/sites/default/files/2022-11/Tutoriel_import_donnees_IGN_PostgreSQL.pdf)
    * En comparaison, les données OSM France entière au format PBF font 4,4 Go (décompressé), ce qui est déjà non-négligeable
    * Cela rendrait obligatoire le travail sur un repo séparé et le déploiement d'une instance y compris pour le développement.

**Comment by MathieuFV** [comment]
https://dialog.beta.gouv.fr/regulations/018b6c8f-98b7-7ff7-9dbb-c92133998644

Un exemple d'arrêté dans lequel le calcul d'intersection aboutit à une UX déroutante.

**Comment by florimondmanca** [comment]
Avec @aureliebaton on a continué l'explo design intersections

## UX possible

Dans le type de localisation "Voie nommée", une voie la case "Voie entière" (#573) décochée, on devrait pouvoir définir les extrémités de la section de voie ("début / fin" ou "point A / point B", naming à voir)

Chaque extrémité pourrait être identifiée avec :

* Un numéro d'adresse
* OU BIEN l'intersection avec une autre voie nommée

Un widget (select, boutons radio... à déterminer) permettrait de choisir un type ou l'autre

Question en suspens sur les POI, notamment les rond-points ? Est-ce qu'on peut les utiliser pour définir une extrémité ? => Actuellement considérer que oui mais que ce ticket se concentre sur les _intersections avec les voies nommées_ (donc pas les extrémités de type POI)

## Waze

On a remarqué que l'outil Waze raisonnait par tronçon (portion de voie entre deux intersections). Il permet de placer des "événements" (points) sur un tronçon.

Pour autant les numéros d'adresse restent utiles. Leur outil permet de définir des numéros de maison mais on n'a pas réussi à les utiliser pour définir les extrémités.

Et on a bien des exemples d'arrêtés formulés par numéros, par exemple Toulouse AT2023-086 :

"ROMENADE HENRI MARTIN (départ), AVENUE DE LA GARONNETTE (n°59 à la DESCENTE DE
LA HALLE AUX POISSONS), PLACE DU PONT NEUF, PONT NEUF, QUAI DE LA DAURADE,
PLACE DE LA DAURADE, PROMENADE HENRI MARTIN (arrivée)"

**Comment by aureliebaton** [comment]
Les maquettes d'exploration sont dispos ici : https://www.figma.com/file/YuT6Uh4wxe90U8LaPLlDzO/Dialog?type=design&node-id=4811%3A16739&mode=design&t=vg2Kk2gKCfY6N81G-1

**Comment by johanricher** [comment]
Pour compléter ce que je disais il y a quelques temps

> En France seule la BAN (qui commence à être utilisée par Google Maps mais sans qu'on puisse vraiment le vérifier) fait référence pour les adresses et fournit la seule source de vérité pour le géocodage.

Info vue dans [le collectif MTECT - IGN des utilisateurs de la BAN](https://osmose.numerique.gouv.fr/jcms/285067008_SocialTopic/fr/quelques-actualites-en-vrac-et-sans-attendre-le-prochain-point-du-25-juin) :

> C'est confirmé : les principaux acteurs du GPS (Google Maps, Waze, Apple Maps, Here et TomTom) utilisent la BAN avec une fréqence à minima mensuelle. Mais tous ne sont pas au mêmes niveau d'exploitation (certains ont encore des trous dans la raquette)
