### ISSUE TITLE
Mise en conformité RGESN (écoconception)

### ISSUE THREAD

**Issue by johanricher** [MTES-MCT/dialog#423]
## Contexte

Le référentiel général d'écoconception des services numériques (RGESN) a pour objectifs de réduire la consommation de ressources informatiques et énergétiques et la contribution à l’obsolescence des équipements.

[La dernière version du référentiel publiée par l'ARCEP le 17 mai 2024](https://www.arcep.fr/mes-demarches-et-services/entreprises/fiches-pratiques/referentiel-general-ecoconception-services-numeriques.html) ([pdf](https://github.com/MTES-MCT/dialog/files/15496861/referentiel_general_ecoconception_des_services_numeriques_version_2024.pdf)) comprend 78 critères. Chaque critère,  présenté sous forme de question, associé à un niveau de priorisation et à une fiche pratique, peut être déclaré comme "validé", "non validé", "en cours" ou "à évaluer" pour évaluer la conformité au RGESN.

Un outil (tableur Excel) a été mis à disposition par l'ARCEP pour faciliter ce travail, et que l'équipe DiaLog utilise dans une démarche d'auto-évaluation. Cette démarche, reprenant les premiers travaux démarrés en août 2023 (cf. archive ci-dessus) a commencé lors d'un atelier le 29 mai 2024 et a vocation à être menée sur la durée, pendant la construction du service DiaLog et accentuée lors des phases ultérieures (accélération, pérennisation) à l'instar de la mise en conformité RGAA (#730).

:arrow_right: [`rgesn_2024_outil_declaration_ecoconception Dialog.xlsx`](https://kdrive.infomaniak.com/app/office/184671/54720)

Cet outil permet de calculer un score d'avancement de la manière suivante :

![image](https://github.com/MTES-MCT/dialog/assets/10212787/a532f26b-a6c8-462f-9863-fe62ad96ade4)

## Implémentation

* [x] Publier une déclaration d'éconception : https://dialog.beta.gouv.fr/ecoconception
* [x] Nommer une personne référente : Florimond Manca
* [x] Finaliser l'auto-évaluation
* [ ] Lister les critères prioritaires et les traduire en tâches implémentables pour DiaLog (tickets sur Github)

<details><summary>Archive août 2023</summary>

## Contexte

Le RGESN (précédente version) comporte 79 critères qui permettent de calculer un score de conformité. Le but étant de pouvoir réaliser un diagnostic de conformité du service numérique (en auto-diagnostic ou un audit externe indépendant).

Un [premier auto-diagnostic](https://docs.google.com/spreadsheets/d/1z9cJkqjeLVFE8aE07hPE7hlTZUmu3_D81HiipQZXFNI/edit) est en cours de réalisation par l'équipe afin d'estimer le niveau de conformité de DiaLog.

Au 23/08/2023, le score de conformité est de 28 sur 79 (35 %), tandis que certains critères ne semblent pas applicables.  Si l'on écarte ces 19 critères, le taux de conformité est de 47 %.

![image](https://github.com/MTES-MCT/dialog/assets/10212787/a7dcec04-c764-494c-8739-1f9458b098a5)

# Implémentation

Cet epic centralise la liste des tâches consacrées à l'implémentation du RGESN. Cette liste pourra évoluer dans le temps. Les tâches non triviales ont vocation à être explorées dans un ou plusieurs tickets.

Chaque tâche doit être priorisée en début d'itération avant d'être implémentée.

* Finaliser [l'auto-diagnostic](https://docs.google.com/spreadsheets/d/1z9cJkqjeLVFE8aE07hPE7hlTZUmu3_D81HiipQZXFNI/edit)
  * [x] Critères 4.5, 4.11, 4.13 : @florimondmanca ou @mmarchois complètent
  * [x] Critère 1.5 : @aureliebaton se renseigne (Voir commentaire plus bas)
* Créer une page de déclaration d'écoconception, qui aurait aussi vocation à servir de support de communication
  * [x] @florimondmanca : [Rédiger le contenu de la page](https://pad.incubateur.net/pN_J9-0HR8GFFTFaEQxviw)
  * [x] @aureliebaton : Relire le contenu
  * [x] @florimondmanca : Implémenter la page #432 
* [x] Désigner une personne référente => @florimondmanca 
* [x] Le documenter sur la page de déclaration #461 
* [x] Faire le test [ecoIndex](https://www.ecoindex.fr/) et le documenter
* [ ] @aureliebaton Refaire une passe sur l'auto-diag, identifier les angles morts et poser des questions à Christophe Clouzeau afin de préciser les ambiguité
* [ ] Critère 1.5 : faire un test browserstack sur une unité fonctionnelle (par exemple créer un arrêté)
  * [ ] Demander la licence open source
  * [ ] Faire les tests 
* [ ] Critère 6.1 : modifier "300 ko" (qui est un poids en données transférées) en "800 ko" (en poids de page entièrement chargé) dans la déclaration écoconception

</details>

**Comment by florimondmanca** [comment]
Pour les 115 bonnes pratiques, les outils pratiques / synthéthiques au-delà du livre sont ceux-ci :

* Checklist excel : https://collectif.greenit.fr/ecoconception-web/2022-05-Ref-eco_web-checklist.v4.xlsx
* Dépôt avec le détail des bonnes pratiques (tout n'est pas repris dans l'excel) : https://github.com/cnumr/best-practices

**Comment by florimondmanca** [comment]
#### Concernant la "mise en conformité"

Au vu de l'état actuel du RGESN, ça ne pourra être fait que sur les items qui sont vérifiables de façon non-ambigüe et répétable (comme on l'a vu lors de l'atelier, ce n'est pas le cas de tous les items, qui sont parfois trop abstraits ou pas encore suffisamment bien rédigés)

En revanche une "mise en conformité" avec les 115 bonnes pratiques est possible puisque cet outil a été conçu pour ça.

Doit-on se baser sur les 115 bonnes pratiques pour la "conformité" et la "déclaration", ou continue-t-on avec le RGESN ?

#### Concernant la page "déclaration écoconception"

Sur quels exemples peut-on s'appuyer ?

Je pense par exemple à la page de Dalkia, qui remplit aussi un objectif pédagogique pour le grand public : https://www.dalkia.fr/site-web-ecologique-explications/

**Comment by johanricher** [comment]
> Doit-on se baser sur les 115 bonnes pratiques pour la "conformité" et la "déclaration", ou continue-t-on avec le RGESN ?

Seul le RGSEN a vocation à devenir une obligation, à l'image du RGAA. C'est donc le cadre à suivre même si le RGESN va devra certainement évoluer avant qu'il devienne une obligation légale (s'il le devient un jour).

Mon interprétation c'est qu'il n'y a pas une correspondance parfaite entre RGESN et 115 BP (et que ces dernières sont par ailleurs plus datées) mais, qu'en revanche, certaines des bonnes pratiques peuvent être reliées à des critères du RGESN et quand c'est le cas elles donnent des lignes directrices plus claires pour leur implémentation que ne le fait le RGESN.

> Concernant la page "déclaration écoconception" sur quels exemples peut-on s'appuyer ?

Cette page sur le site ademe.fr a été citée en exemple : https://www.ademe.fr/une-logique-d-ecoconception/

**Comment by astranchet** [comment]
En complément d'une page Déclaration d'écoconception et de l'item « Faire le test [ecoIndex](https://www.ecoindex.fr/) et le documenter », GreenIt propose un framework de [déclaration environnementale](https://declaration.greenit.fr/). C'est un peu différent car elle n'est pas reliée au RGESN, c'est plutôt une déclaration qui indique le niveau d'écoconception moyen du site (basé sur l'écoindex), et du détail.

**Comment by florimondmanca** [comment]
> (et que ces dernières sont par ailleurs plus datées)

Les 115 BP ont été initiées il y a de nombreuses années mais elles sont régulièrement mises à jour, elles ne me semblent donc pas "datées" au sens de "moins applicables aujourd'hui".

**Comment by aureliebaton** [comment]
@florimondmanca Revue effectuée de la déclaration d'écoconception. J'ai fait quelques modifications et ajouter une partie sur l'évaluation du parcours avec GreenIT Analysis.
Pour une première version ça me semble bien, merci beaucoup pour ce travail. Il faudra qu'on la complète au fur et à mesure lorsqu'on aura défini les prochaines étapes.

**Comment by aureliebaton** [comment]
Au sujet du critère 1.5 "Le service numérique est-il utilisable sur des terminaux de 5 ans et plus ?"
 j'ai posé la question à Chrsitophe Clouzeau de Temesis et qui a participé à la rédaction et à la mise en oeuvre du RGESN. Voici quelques éléments de réponse.
 Lorsqu'eux mêmes conduisent des audits, ils vérifient que le service fonctionne sur des vieux appareils qu'ils ont à dispo : 
-  iPhone
- Android
- PC
- Mac de 2011
- Linux

Ce n'est pas gênant si la qualité de service est dégradée mais par contre on doit pourvoir naviguer et compléter la tâche.

Cela permet de vérifier certaines choses, par exemple, sur le Mac de 2011, il y a une vieille version de Safari qui peut pas être mise à jour (OS pas à jour, ni navigateur), donc YouTube ne marche pas.

**Comment by florimondmanca** [comment]
@aureliebaton Merci pour les infos sur le 1.5. Estèce que des versions cibles d'iPhone, Android, Linux (Ubuntu ?), PC (Windows ?) ont été citées ? "Vieux" à quel point ?

On n'a pas de tel matériel à dispo mais on pourrait utiliser Browserstack qui met à dispo un navigateur tournant sur un vrai appareil. La liste des appareils proposés est ici : https://www.browserstack.com/list-of-browsers-and-platforms/live

**Comment by aureliebaton** [comment]
Je lui avais parlé au téléphone et il n'avait pas toutes les infos sous la main, mais d'après ce que j'ai compris il faut au moins que le matériel ait plus de 5 ans et ensuite ça dépend de ce qu'on sous la main. Par exemple, ils avaient à dispo un mac de 2011 donc ils font les tests avec. Pour PC oui c'était avec Windows je crois. 
Pour Browserstack, c'est top, ça me parait être un bon compromis, je peux poser la question à Christophe. 
Sinon on peut aussi regarder ce qu'on a chez nous, par exemple j'ai un PC de 2010 ou 2011 (avec Windows 10) donc je pourrais éventuellement faire un test dessus.

**Comment by florimondmanca** [comment]
La déclaration écoconception vient d'être mergée #432 

D'après la liste de todo sur ce ticket, il ne reste "plus qu'à" désigner la ou les personnes référentes écoconception.

Je suis ok pour l'être, est-ce qu'il faut d'autres personnes ?

**Comment by aureliebaton** [comment]
Ok super, ça me va bien que tu sois référent. Je peux être référente suppléante si besoin ;-)

**Comment by aureliebaton** [comment]
Au sujet du critère 1.5, j'ai posé la question à Christophe Clouzeau, il va vérifier auprès de Julien Whilem pour browserstack mais il pense que c'est une bonne alternative si on a pas le matériel à dispo. On pourra créer une story la-dessus pour définir les tests correspondant à ce critère.

**Comment by aureliebaton** [comment]
Il restait la question du calcul du score que @astranchet avait posé à Richard par email et dont j'ai parlé avec Christophe aussi. Il y a eu plusieurs discussions à ce sujet et il est possible que le calcul évolue.

**Comment by florimondmanca** [comment]
@aureliebaton Je propose d'ajouter le référent dans la partie "Stratégie et objectifs" de la déclaration, tu peux regarder ce que ça donne ici : https://dialog-staging-pr461.osc-fr1.scalingo.io

Ça te semble OK ?

**Comment by johanricher** [comment]
J'ai mis à jour la description du ticket suite à notre atelier RGESN d'hier s'appuyant sur la nouvelle version du référentiel sortie il y a 2 semaines.
