### ISSUE TITLE
En tant que contributeur je peux définir la localisation géographique où s’applique une réglementation afin qu'elle soit communiquée aux GPS

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#43]
## User story

En tant que contributeur je peux définir la localisation géographique où s’applique une réglementation afin qu'elle soit communiquée aux GPS

## Critères d'acceptation

* _(Must have MVP)_ Remplissage manuel
  * [x] Le formulaire permet de définir manuellement une portion de rue
  * [x] Une seule rue est demandée et obligatoire
  * [x] Les informations suivantes sont prévus :
    * Code postal
    * Ville
    * Rue
    * Numéro de début
    * Numéro de fin
  * [ ] #175
  * [x] Il est possible de modifier ces données après la création d'une réglementation
  * [x] Les données de localisation sont retranscrites dans le flux DATEX II
* _(Nice to have)_
  * [ ] Une aide à la saisie (autocomplétion) est proposée pour le code postal, la ville, la rue
  * [ ] Il est possible de définir une réglementation "ville entière" (aucune rue à préciser). Cela nécessite une action explicite de l'utilisateur. [À reprioriser - pas de cas d'usage]
  * [ ] Il est possible de définir plusieurs rues concernées par la réglementation.
* _(Could have - plus tard)_
  * Validation visuelle avec une carte
  * Choix d'une rue (voire ensemble de rues) sur la carte
  * Partir d'un itinéraire et sélectionner des rues qui l'intersectent (effet waou)

## Design

_c.f._ [Maquette](https://www.figma.com/file/YuT6Uh4wxe90U8LaPLlDzO/Dialog?node-id=6%3A2&t=UT9p4kKSlLVGChAH-0)

* Code postal
* Ville
* 1 rue
  * Nom de rue
  * Numéro de début
  * Numéro de fin

## Implémentation

Approche générale

* Données : les données de l'étape "Localisation" (ville et rue) seront représentées par une entité `Location`
* Affichage : les données seront définies dans des champs dans l'étape "Localisation" du formulaire multi-étapes (cf #80)
* DATEX II : utiliser comme `LocationReference` une instance de `LinearWithinLinearElement` pour la rue concernée - cf [wiki](https://github.com/MTES-MCT/dialog/wiki/Comment-utiliser-DATEX-II#une-rue-o%C3%B9-sapplique-une-r%C3%A9glementation) 
  * Le `fromPoint` et `toPoint` (coordonnées GPS latitude-longitude) seront obtenues à l'aide d'une API de géocodage

Tâches

* [x] Étendre le MCD avec les champs de la maquette (ADR 2) https://github.com/MTES-MCT/dialog/pull/81
* [x] Implémenter les champs de la maquette côté backend (BDD, domaine, commandes) et les ajouter au formulaire
  * #84 
* [x] Rédiger une ADR concernant l'approche de géocodage #94
* [x] Lors de la création, transcrire les numéros de début et de fin en coordonnées GPS à l'aide de l'API de géocodage et les stocker dans des champs dédiés
  * #89
* [x] Inclure les données dans l'export DATEX II au format indiqué ci-dessus #102
* [ ] Comment prendre en compte une "rue entière" (pas de numéros de début et de fin) ? Peut-on faire seulement un numéro de début, et seulement un numéro de fin ?
