### ISSUE TITLE
En tant que contributeur je veux définir les caractéristiques des véhicules concernés par la réglementation afin qu'elles soient communiquées aux GPS

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#44]
## User story

En tant que contributeur je veux définir les caractéristiques des véhicules concernés par la réglementation afin qu'elles soient communiquées aux GPS

## Critères d'acceptation

(Propositions @florimondmanca à partir des discussions et maquettes, TODO @MathieuFV revoir la pertinence de ce qui suit)

* [ ] (Obligatoire) Il est _possible_ (mais pas requis) de définir un **type de véhicule** concerné défini par une ou plusieurs de ces **caractéristiques** : 
  * [x] le poids maximal\* (\*maximal = la réglementation s'applique au-delà de cette valeur)
  * [x] la longueur maximale
  * [x] la largeur maximale
  * [x] la hauteur maximale
  * [ ] l'usage (affectation)
* [ ] (Obligatoire) Il est possible de définir plusieurs types de véhicules (opération "A OU B")
* [ ] (Obligatoire) Il est possible d'ajouter une exception à un type de véhicule (opération "A ET NON-B")
* [ ] (Obligatoire) Il est possible de modifier un type de véhicule une fois défini
* [ ] (Obligatoire) Il est possible de supprimer un type de véhicle une fois défini
* [ ] (Obligatoire) Les types de véhicules sont reflétés dans le récapitulatif (dernière étape du formulaire)
* [ ] (Obligatoire) Les types de véhicules sont reflétés dans la fiche d'une réglementation
* [ ] ...

## Design

* [Maquette Figma](https://www.figma.com/file/YuT6Uh4wxe90U8LaPLlDzO/Dialog?t=jYvZNviVekfZVmdd-0)

## Implémentation

* [x] Champs basiques #73
* [ ] #176
* [ ] Ajout d'autres types de véhicules
* [ ] Ajout d'exception(s) à un type de véhicule
* [ ] Intégration au formulaire "étape par étape"
