### ISSUE TITLE
Champ "Vitesse" dans le cas d'une limitation de vitesse

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#472]
## User story

ETQ utilisateur de l'interface de saisie, j'indique la vitesse maximale autorisée d'une mesure de limitation de vitesse afin qu'elle apparaisse dans les exports (Word, GPS)

## Critères d'acceptation

- [x] _(Must have)_ Un champ "Vitesse maximale autorisée" apparaît quand on choisit le type de restriction "Limitation de vitesse"
- [x] _(Must have)_ Ce champ est de type numérique (il s'agit d'un nombre de km/h)
- [x] _(Must have)_ La vitesse choisie apparaît dans l'affichage "lecture seule" de la localisation : "Vitesse limitée à XX km/h pour [véhicules...]"
- [ ] Les arrêtés créés dans l'application DiaLog avec des restrictions de vitesse sont [exposés en Datex II](https://dialog.beta.gouv.fr/api/regulations.xml) (iso avec l'UI).
- [ ] Les arrêtés créés dans l'application DiaLog avec des restrictions de vitesse peuvent être exportés au format `.docx` (iso avec l'UI).

## Design

Voir [Maquette](https://www.figma.com/file/YuT6Uh4wxe90U8LaPLlDzO/Dialog?type=design&node-id=6-2&mode=design&t=CfaAFROSfUy3smQp-0)

## Contexte supplémentaire

Actuellement, on peut seulement indiquer le type "Limitation de vitesse" mais pas préciser la vitesse en question

## Implémentation

* #482
* #498
