### ISSUE TITLE
Champs caractéristiques poids lourds

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#473]
## User story

ETQ utilisateur de l'interface de saisie, je précise les caractéristiques des poids lourds concernés par la restriction afin de préciser lesquels sont concernés

## Critères d'acceptation

- [ ] _(Must have)_ De nouveaux champs s'affichent lorsqu'on sélectionne le type de véhicule "Poids lourds" : "Poids maximum", "Largeur maximum", "Longueur maximum", "Hauteur maximum"
- [ ] _(Must have)_ À l'inverse, ces champs disparaissent quand on déselectionne "Poids lourds"
- [ ] _(Must have)_ "Poids maximum" est obligatoire avec une valeur par défaut de 3,5 tonnes
- [ ] _(Must have)_ Les autres champs sont optionnels et n'ont pas de valeur par défaut
- [ ] _(Must have)_ Les champs caractéristiques ne sont pas réinitialisés quand on toggle la catégorie "Poids lourds" côté client
- [ ] _(Must have)_ Les champs caractéristiques sont réinitialisés si on retire la catégorie "Poids lourds" et qu'on enregistre
- [ ] _(Must have)_ Les caractéristiques remplies apparaissent dans l'export DATEX II
  - NB : les caractéristiques se combinent par un "OU" : vérifier si on peut tout mettre dans un seul `VehicleCharacteristics`, ou s'il faut créer un `ConditionSet` combinant plusieurs `VehicleCondition` par `OR`
- [ ] _(Must have)_ Les caractéristiques remplies apparaissent dans l'export Word

## Design

Voir [Maquette](https://www.figma.com/file/YuT6Uh4wxe90U8LaPLlDzO/Dialog?type=design&node-id=2367-137066&mode=design&t=CfaAFROSfUy3smQp-0)

Affichage :

> Circulation interdite pour les poids lourds de plus de 3,5 tonnes, plus de 10 mètres de long, ou plus de 2,80 mètres de haut

Export Word : voir [Modèle](https://kdrive.infomaniak.com/app/office/184671/26456)

## Implémentation

TODO revue de conception

Ce ticket peut être découpé en plusieurs étapes / PR

* Champ "Poids maximum"
* Champ "Largeur maximum"
* Champ "Longueur maximum"
* Champ "Hauteur maximum"
* Pour chaque champ implémenté :
  * Affichage dans la vue lecture
  * Export Word modifié
  * Export DATEX II modifié

Proposition

* Ajouter champs à `VehicleSet` directement : `private ?float $heavyweightMaxWeight`
* Contrôler le statut "required" (pour le poids max) par le formulaire et des checks de validation

## Contexte supplémentaire

Pour l'instant on peut seulement dire que la restriction s'applique à TOUS les poids lourds, quelles que soient leurs caractéristiques
