### ISSUE TITLE
Catégorie de véhicule "Crit'Air" unifiée

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#474]
## User story

ETQ utilisateur de l'interface de saisie, je sélectionne librement quelles vignettes Crit'Air sont concernées par la restriction afin de ne cibler que ces vignettes-là

## Critères d'acceptation

- [x] _(Must have)_ Les catégories "Crit'Air 4" et "Crit'Air 5" sont regroupées en une seule catégorie "Crit'Air"
- [x] _(Must have)_ Quand on sélectionne "Crit'Air", un champ checkboxes s'affiche pour sélectionner à quelles vignettes Crit'Air la restriction s'applique
- [x] _(Must have)_ Les vignettes 4 et 5 sont sélectionnées par défaut
- [x] _(Must have)_ Les vignettes ne sont pas réinitialisées quand on toggle "Crit'Air" côté client
- [x] _(Must have)_ Les vignettes sont réinitialisées quand on déselectionne "Crit'Air" et qu'on enregistre (lors de la prochaine édition, les checkboxes s'afficheront dans leur état par défaut)

## Design

Voir [Maquette](https://www.figma.com/file/YuT6Uh4wxe90U8LaPLlDzO/Dialog?type=design&node-id=2367-137066&mode=design&t=CfaAFROSfUy3smQp-0)

## Implémentation

TODO revue de conception

DB : prévoir une migration de données ? critair4, critair5 -> critair + valeurs des vignettes concernées

## Contexte supplémentaire

Actuellement on a 2 catégories distinctes "Crit'Air 4" et "Crit'Air 5", ce qui fait d'ailleurs qu'on ne peut pas préciser les vignettes 3 ou inférieure, sauf à utiliser le champ "Autres"
