### ISSUE TITLE
Evolution des types de véhicules concernés

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#475]
## Critères d'acceptation

- [ ] _(Must have)_ Une catégorie "Matières dangeureuses" est ajoutée au Types de véhicules concernés
- [ ] _(Must have)_ Dans les exceptions, la catégorie "Véhicules sanitaires" devient "Véhicules d'urgence"
- [ ] _(Must have)_ Dans les exceptions, la catégorie "Bus" devient "Transports en commun"
- [ ] _(Must have)_ Dans les exceptions, ajout des catégories "Taxis et VTC" et "Covoiturage"
  - NB : Ne pas ajouter "Desserte locale", encore en exploration
- [ ] _(Must have)_ Les nouvelles catégories sont traitées par l'affichage, l'export Word et l'export DATEX II

## Design

Voir [Maquette](https://www.figma.com/file/YuT6Uh4wxe90U8LaPLlDzO/Dialog?type=design&node-id=2373-138457&mode=design&t=CfaAFROSfUy3smQp-0)

## Implémentation

TODO revue de conception

DATEX II : voir [Nomenclature.xlsx](https://kdrive.infomaniak.com/app/office/184671/26231) pour la valeur DATEX II qu'on pourrait utiliser pour les nouvelles catégories

DB : prévoir une **migration de données** ? Ex : pour changer automatiquement VehicleSet avec type = 'bus' en type = 'public_transport'
