### ISSUE TITLE
En tant que service numérique, je récupère la réglementation de DiaLog afin de l’utiliser lors d’un calcul d’itinéraire ou de l’afficher sur ma carte 

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#48]
**User story**

cf titre

**Contexte additionnel**

Actuellement on a un fichier d'exemple statique : https://dialog.beta.gouv.fr/sample.xml

Le but est d'exposer de façon dynamique la réglementation ajoutée au système

**Critères d'acceptation**

* Indispensable :
  * [x] Le fichier d'exemple statique /sample.xml est conservé pour l'instant (on l'a communiqué aux GPS)
  * [ ] Les réglementations stockées en base de données sont accessibles au format XML DATEX II sur /api/regulations.xml
* Agréable :
  * L'endpoint XML est garanti conforme au format DATEX II (validation à partir des fichiers XSD)

**UI**

* Page d'accueil : lien vers l'endpoint "Voir le flux DATEX II"

**Implémentation**

* [ ] Query `GetAllRegulationOrders()` et controller qui expose le résultat de cette requête au format XML DATEX II #66
