### ISSUE TITLE
Visas d'un arrêté

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#557]
## User story

_En tant que secrétaire de mairie, j'utilise DiaLog pour rédiger mes arrêtés sans faire d'erreurs sur les visas_

Romain Veldeman, brigadier de gendarmerie à Gisors, nous a sollicité pour en savoir plus sur DiaLog. Lors de notre discussion, il a formulé plusieurs pistes d'amélioration qui sont retranscrites dans le Pad CR (voir "[2023-11-16 - Discussion avec R. Veldeman (Gendarmerie Gisors)](https://pad.incubateur.net/MaOMoW0QS82FIj5oAABVAw?both#2023-11-16---Discussion-avec-R-Veldeman-Gendarmerie-Gisors)").

Parmi les éléments amenés par Romain, il a beaucoup insisté sur les difficultés que peuvent rencontrer les secrétaires de mairie concernant la rédaction des arrêtés de circulation. En effet ces arrêtés doivent, pour être valide, comporter plusieurs éléments (dont on peut trouver une liste complète sur [ce site](https://www.collectivites-locales.gouv.fr/institutions/les-arretes-et-deliberations#__RefHeading__23_943205690Cordialement,)). Parmi ces éléments sont les "visas", désignant les documents annexes qui sont cités au début de l'arrêté **afin de procurer une base légale légitimant les dispositions qui y sont prises (*).**

Sans ces annexes, l'arrêté n'a aucune valeur juridique, de même que si ces dernières sont mal rédigées, le document entier peut être attaqué sur cette base afin de faire sauter toute sanction consécutive à un infraction au dispositif énoncé. Si je grille un stop et que je suis arrêté, mais que les visas de l'arrêté qui dispose de la présence du stop sont mal rédigés, le bon avocat saura faire sauter mon amende et me rendre mes points de permis sans problème.

Ainsi, le sujet de l'aide à la rédaction des visas prend une importance qui dépasse la seule problématique des erreurs de syntaxe ou de références, car c'est tout l'impact de la réglementation qui dépend de cette bonne rédaction.

Par ailleurs le témoignage de R. Veldeman montre que la rédaction de ces visas comporte une véritable technicité (savoir faire juridique) qui n'est pas toujours maîtrisée de la part des rédacteurs des arrêtés (faute de formation ou de temps à dédier à la rédaction des actes administratifs, voir : "On a des secrétaires de mairies qui n'ont parfois que 3h de services par semaine dans certaines communes."). Ces problèmes de rédaction des arrêtés se répercutent directement sur le terrain puisque la réglementation n'est pas efficace, ces problématiques sont naturellement pesante pour les élus qui en retour mettent vraisemblablement la pression sur les secrétaires de mairie, qui ne disposent que de peu de ressources afin d'améliorer la situation.

Il y a donc un vrai enjeu dans DiaLog de mettre à disposition de telles ressources, en proposant des fonctionnalités dédiées. Le présent ticket couvre à la fois l'exploration et le design de ces fonctionnalités, l'implémentation pourra au besoin faire l'objet d'un nouveau ticket.

_(*) : "Les "visas" indiquent les textes en application desquels le maire prendra son arrêté (articles du code concerné, lois, décrets et arrêtés applicables)." Les visas sont donc des références à des documents nationaux (lois et décrets qui paraissent au Journal Officiel et sont consultables sur Légifrance, mais aussi des références à des arrêtés qui peuvent être pris au niveau local, et ne sont donc parfois connus que de la commune concernée. On trouve aussi parfois des références à la demande d'arrêté déposée par une entreprise dans le cadre de travaux qui ont lieu sur l'emprise d'une voirie_

## Critères d'acceptation

- [x] _(Must have)_ Il est possible dans l'interface de DiaLog d'ajouter une liste de visas à un arrêté
- [x] _(Must have)_ Les visas sont rédigé par la syntaxe "Vu le..."
- [x] _(Must have)_ Les visas rédigés dans DiaLog se retrouvent dans l'export word de l'arrêté
- [ ] _(Nice to have)_ Des visas sont automatiquement proposés en fonction du type d'arrêté et/ou des restrictions de circulation qui sont renseignées dans le dispositif
- [x] _(Nice to have)_ DiaLog dispose d'une bibliothèque de visas utilisables dans les arrêtés rédigés par les utilisateurs
- [x] _(Nice to have)_ L'interface permet de parcourir la bibliothèque de visas ou de rédiger soi-même le visa
- [x] _(Nice to have)_ Des infobulles (ou un autre élément d'interface) permettent d'expliquer la fonction les visas qui sont annexés à l'arrêté
- [ ] _(Nice to have)_ Si l'utilisateur souhaite publier un arrêté dont la base légale est incomplète (par exemple : Si un utilisateur a supprimé un visa qui pourtant est nécessaire au vu du type d'arrêté et/ou des restrictions du dispositif, un avertissement lui est transmis au moment de valider la liste des visas).

**Comment by johanricher** [comment]
Il me semble que [la page](https://www.collectivites-locales.gouv.fr/institutions/les-arretes-et-deliberations) que tu cites dans le ticket contredit ce que tu dis par ailleurs :

> [les arrêtés] ne doivent respecter aucune forme déterminée

>  l’absence de visa n’est pas de nature à entraîner l’annulation de [l'arrêté] (...) Cependant, il vaut mieux [que les "visas", les "considérants", le "dispositif" soient présents]

Il s'agit si je comprends bien d'une recommendation ou d'une bonne pratique pluôt qu'une obligation qui est cadrée juridiquement. C'est donc de l'ordre de l'informel, ce qui peut nous poser problème pour savoir comment justement formaliser ça : quelle est la légimité de DiaLog de dire comment motiver un arrêté ? La responsabilité de la DGITM ne serait-elle pas engagée si un arrêté créé avec DiaLog est cassé parce que "mal motivée" ?

Quoi qu'il en soit, si on se base sur le besoin remonté par cette personne, le coeur du sujet serait en quelque sorte d'aider les agents à motiver un arrêté ("Des visas sont automatiquement proposés en fonction du type d'arrêté et/ou des restrictions de circulation qui sont renseignées dans le dispositif").

Les articles du code de la route et du code général des collectivités territoriales, qui motivent de manière générale les restrictions de circulation, pourraient systématiquement être insérées en début d'arrêté à l'export au format .docx. Ca suffirait ?

Est-ce qu'il y a des textes règlementaires à des "types" d'arrêté en particulier ? Sachant que les "types" d'arrêté ou plutôt  ce qu'on appelle "Nature de l'arrêté" dans l'UI de DiaLog (actuellement "Travaux", "Règlementation permanente", "Incident ou péril", "Evenement", "Autre") ne reposent il me semble sur aucun formalisme juridique. Ca me paraît être une base un peu fragile pour un moteur de règles qui se veut juridiquement solide ("si la nature de l'arrêté est Travaux, alors il faut insérer tel article de tel code...").

**Comment by MathieuFV** [comment]
J'ai trouvé une ressource très intéressante [ici](https://www.creuse.gouv.fr/contenu/telechargement/4817/34922/file/guide_de_la_police_de_la_circulation.pdf).

Qui définit de manière exhaustive les types d'arrêtés permanents et temporaires. Selon ce document :

**Les arrêtés permanents peuvent concerner :** 

- Régime de priorité aux carrefours : feux de circulation, balise de priorité, stops, carrefour giratoire,
- Limites d'agglomération,
- Réglementation de la vitesse,
- Réglementation du stationnement,
- Sens unique ou interdit,
- Sens prioritaire,
- Interdiction de dépasser,
- Interdiction de circuler à certains types de véhicules du fait de la catégorie de ceux-ci ou par limitation de
hauteur, de tonnage, de longueur ou de largeur,
- Interdiction de tourner.

**Les arrêtés temporaires peuvent concerner :** 

Travaux : l'entreprise chargée des travaux demande par écrit la prise de mesures concernant la circulation. Cette
demande doit préciser :
- la durée et la période du chantier,
- l'utilisation faite du domaine public pendant cette période,
- les risques encourus, par l'entreprise et par tout usager,
- les moyens de protection de la circulation qu'elle propose.

Manifestation : l'organisateur demande par écrit la prise de mesures au titre de la police de la circulation. Cette
demande doit préciser :
- la date et les horaires de la manifestation,
- la voirie concernée et la localisation exacte de la gêne occasionnée,
-  l'utilisation que l'organisateur entend faire de la voie,
- les moyens de sécurité et de protection qu'il se propose de mettre en œuvre.

Ces arrêtés peuvent concerner : 
- Les mêmes mesures que les arrêtés permanents énoncées ci-avant, à l'exclusion des limites d'agglomération,
- La mise en place d'une déviation de circulation,
- La réduction à une voie de circulation avec un alternat par feux, panneaux ou manuel,


Conclusion : Selon ce document on aurait tendance à vouloir faire évoluer la manière dont on demande de renseigner le type d'arrêté. Aujourd'hui on a un champ "Nature de l'arrêté" qui permet de définir un type, mais la liste déroulante contient des catégories qui peuvent se retrouver à la fois dans un arrêté permanent ou temporaire, c'est un peu confusant (voir image)

![Types d'arrêtés actuels](https://github.com/MTES-MCT/dialog/assets/65396841/e8670ac8-c311-4162-9a98-0f5c5d5d75ff)

On pourrait aller vers la solution suivante (**Proposition à discuter**) :

- Un switch permet de définir si l'arrêté est **Permanent** ou **Temporaire** avant le champ "Nature de l'arrêté"
- On renomme le champ "Nature de l'arrêté" en "Type d'arrêté"
- Sous le champ "Type d'arrêté" apparait une explication du type "Selon le type d'arrêté renseigné, DiaLog vous fournira des conseils concernant sa rédaction".

Si on choisit un arrêté Permanent : 

- L'arrêté acquiert le type "Permanent"
- Le champ date de fin d'effet de l'arrêté reste grisé et vide.
- Le champ "Type d'arrêté" propose les catégories suivantes : "Réglementation de la vitesse", "Sens unique ou interdit", "Interdiction de circulation", "Autre"
- Le choix du type "Autre" ouvre un champ texte permettant de désigner le type d'arrêté (optionnel)

NOTA : Dans le cas du choix d'un arrêté Permanent, le type de restrictions qui peuvent être insérées par la suite dans le dispositif dépendront du type d'arrêté choisi. Par ex. le choix du type "Réglementation de la vitesse" empêche de renseigner des interdictions de circulation. Ceci n'est pas valable pour un arrêté temporaire où tous les types de restrictions peuvent être renseignés dans un même arrêté.

Si on choisit un arrêté Temporaire : 

- L'arrêté acquiert le type "Temporaire"
- Le champ de date de fin d'effet de l'arrêté est modifiable et ne peut pas rester vide avant de passer à l'étape suivante
- Le champ "Type d'arrêté" propose les catégories suivantes : "Travaux", "Manifestation", "Incident ou péril", "Autre"
- Le choix du type "Autre" ouvre un champ texte permettant de désigner le type d'arrêté (optionnel)

**Comment by MathieuFV** [comment]
En réponse à ton commentaire Johan (il a croisé le mien) : 

1. En effet plus tard dans mes recherches je suis tombé sur [ça](https://www.seine-et-marne.gouv.fr/contenu/telechargement/49295/361802/file/Fiche+s%C3%A9curisation+arr%C3%AAt%C3%A9s+de+police.pdf), où il est marqué : 

> S’agissant des pouvoirs de police spéciale, il y a lieu de souligner que lorsque la loi a attribué une compétence exclusive à une autre autorité (ex. : État), il n’est pas possible pour le maire d’intervenir au titre du pouvoir de police générale pour réglementer en la matière, y compris en cas de circonstances locales particulières. Le maire peut, par contre, intervenir, en cas de péril imminent (Conseil d’État, 2 décembre 2009, commune de Rachecourt-sur-Marne, n°309684).

La police de la circulation et du stationnement étant comprise dans les polices dites "Spéciales".

Ca va dans le sens de dire que la forme de l'arrêté importe peu. Mais on voit aussi [ici](https://www.alexia.fr/fiche/11215/les-3-questions-a-se-poser-pour-contester-un-arrete-municipal-de-police.htm) que : 

> Les mesures de police prises dans l'arrêté ne doivent pas être en contrariété avec une norme supérieure (loi, décret, arrêté préfectoral) ou méconnaitre son champ d'application.

Ce qui va dans le sens de ma première analyse des masques d'arrêtés qui nous ont été transmis par Fronton et Romain Veldeman : Les visas concernent surtout la justification du fait que les mesures énoncées dans le dispositif font bien partie du champ d'application du pouvoir de l'autorité concernée (i.e "Le maire a droit d'interdire la circulation parce que..."). C'est à confirmer via une analyse approfondie.

Sur le sujet plus large de la responsabilité de la DGITM ou de DiaLog, j'ai la même analyse que jusqu'à présent : Tout comme l'utilisateur s'engage à ne fournir que des données qui sont conformes à celles d'un document opposable faisant foi (l'arrêté signé du maire), DiaLog ou la DGITM ne fournit à l'utilisateur que des suggestions de rédaction de l'arrêté qui n'engagent pas la responsabilité de la DGITM en cas de litige. De la même manière que le résultat de ces fonctionnalités d'aide à la rédaction n'est que d'enrichir l'export word de l'arrêté, qui doit toujours être relu et corrigé avant signature.

Pour moi il n'y a pas de blocage lié à la responsabilité potentielle de la DGITM sur ce qui sort de DiaLog, ce serait différent si par exemple on développait un OCR qui enregistre les données à partir d'un PDF fourni par une collectivité. Si l'OCR DiaLog se trompe et abouti à des erreurs dans les données, à ce moment là la DGITM serait vraisemblablement tenue responsable.

Il faudra néanmoins finir par travailler sur les "CGU" et/ou disclaimer pour que tout ça apparaisse clairement...

**Comment by MathieuFV** [comment]
Toujours dans [le guide rédigé par le département de la Creuse](https://www.creuse.gouv.fr/contenu/telechargement/4817/34922/file/guide_de_la_police_de_la_circulation.pdf) on trouve :

 **Les visas :** 

Ils font référence aux textes qui régissent le domaine de l'arrêté et justifient la procédure.

 _La loi n°82-213 du 2 mars 1982 modifiée_

Modifiée par plusieurs textes et notamment par la loi 96-142 du 21 février 1996 relative à la partie
législative du Code Général des Collectivités Territoriales, cette loi traite des droits et libertés des
communes, des départements et des régions,

 _La loi n°83-8 du 7 janvier 1983 modifiée_

Modifiée par plusieurs textes et notamment par la loi 96-142 du 21 février 1996 relative à la partie
législative du Code Général des Collectivités Territoriales, cette loi traite de la répartition des compétences
entre les communes, les départements, les régions et l'état.

_Code général des collectivités territoriales_

Définit les pouvoirs de police du maire dans l'agglomération pour toutes catégories de voies
 
_Code de la Route_

- Régit l'usage des voies ouvertes à la circulation publique et définit le sens de certains termes utilisés dans ce
code. 
- Définit les pouvoirs généraux de police sur les voies ouvertes à la circulation publique autres que les
autoroutes.
- Traite du respect de la signalisation routière
- Traite de l'organisation de manifestations sportives sur les voies ouvertes à la circulation publique.
- **Chaque arrêté doit par ailleurs viser les articles du Code de la Route se rapportant à son objet.**

L’arrêté interministériel du 24 novembre 1967 modifié relatif à la signalisation des routes et autoroutes :
- Fixe les règles d'utilisation de la signalisation routière
 
L’instruction interministérielle sur la signalisation routière :
Cette instruction est divisée en 8 parties :
- 1ère partie : Généralité (arrêté du 7 juin 1977 modifié)
- 2ème partie : Signalisation de danger (arrêté du 7 juin 1977 modifié)
- 3ème partie : Intersection et régime de priorité (arrêté du 24 juillet 1974 modifié)
- 4ème partie : Signalisation de prescription absolue (arrêté du 7 juin 1977 modifié)
- 5ème partie :Signalisation d'indication et des services (arrêté du 31 juillet 2002 modifié)
- 6ème partie : Feux de signalisation permanents (arrêté du 21 juin 1991 modifié)
- 7ème partie : Marques sur chaussée (arrêté du 16 février 1988 modifié)
- 8ème partie : Signalisation temporaire (arrêté du 6 novembre 1992 modifié)

Elle définit la nature de la signalisation et les règles de mise en place, les caractéristiques des panneaux ou
marques sur chaussée, couleur, forme et dimensions. Elle est disponible sur le site de la sécurité routière
www.securiteroutiere.equipement.gouv.fr,: Documentation – Les textes de référence – La route – Signalisation
routière.

Conclusion : Si je lis bien entre les lignes le seul visa qui doit changer d'un arrêté à l'autre est celui qui fait mention du bon article du code de la route, les autres sont relativement constants. A confirmer par la suite...

**Comment by MathieuFV** [comment]
Et maintenant un mot sur le Code des Relations entre le Public et l'Administration (CRPA).

C'est dans ce code que l'on trouve les dispositions législatives qui définissent la validité des actes administratifs. La partie qui nous intéresse plus particulièrement est le Livre II qui concerne les actes unilatéraux pris par l'administration, dont les arrêtés de circulation et de stationnement font partie.

Pour aller plus loin sur la discussion qui concerne la responsabilité de DiaLog par rapport aux données qui y sont saisies, le Chapitre II dispose que "Toute décision prise par une administration comporte la signature de son auteur ainsi que la mention, en caractères lisibles, du prénom, du nom et de la qualité de celui-ci.", ce qui confirme que seul l'arrêté signé en sortie de DiaLog n'a de valeur juridique.

Au passage, le CRPA dispose aussi que la signature électronique est possible, tant qu'elle est établie conformément aux référentiel général de sécurité mentionné dans[ l'ordonnance n°2005-1516 du 8 décembre 2005.](https://www.legifrance.gouv.fr/affichTexteArticle.do?cidTexte=JORFTEXT000000636232&idArticle=LEGIARTI000006317203&dateTexte=&categorieLien=cid).

**Comment by johanricher** [comment]
Je vois les évolutions de ce travail dans les échanges et sur les maquettes, et j'ai l'impression qu'on tend effectivement vers ce que j'appelais plus haut un "un moteur de règles", dans le sens où on prend en entrée différents paramètres ("type d'arrêté", type d'autorité à l'origine de l'arrêté, etc.) pour donner en sortie des "visas".

Afin de rendre ce travail le plus exhaustif possible et afin d'avoir un format structuré qu'il sera plus facile de corriger et de prendre en compte quand viendra le moment de l'implémentation, que pensez-vous de formaliser ces règles dans un format texte ou tableur dans un premier temps ?

**Comment by MathieuFV** [comment]
Suite à la prise de contact de La Rochelle, nous avons pu échanger (entre autres) sur le sujets de visas/considérants :

> Où se complètent les considérants ? doit-on les compléter à chaque fois  ou peut-on uploader des modèles qui serviront ensuite au choix lors de la rédaction de l'arrêté ?

Ce qui suggère des pistes de solutions pour l'implémentation des visas (et considérants).

Pour mémoire, la réflexion de départ sur ce sujet portait vers une solution qui permettrait de générer les visas en fonction des restrictions de circulation exprimées dans l'arrêté par l'utilisateur. 

La première problématique est qu'il ne semble pas y avoir de règle formelle qui permet d'établir la correspondance mesure => visa (conclusion après plusieurs relances infructueuses auprès du [CNFPT](https://www.cnfpt.fr/) pour avoir un contact juridique sur le sujet). 

L'autre problème est qu'il semble qu'à une mesure donnée, deux organisations n'auront pas les mêmes pratiques en matière de visas, et vu ce qui a été dit juste avant, ces deux pratiques sont _susceptibles_ d'être valides juridiquement.

Ceci porte à croire qu'il est nécessaire d'offrir la possibilité aux utilisateurs de renseigner les visas de manière libre plutôt que de contraindre la rédaction ou de générer les visas automatiquement, en tout cas dans un premier temps. Le recueil des données fournies par les utilisateurs aidera peut être à déterminer des modèles d'arrêtés standards, mais nous n'avons pas cette connaissance pour le moment.

Voici alors les conclusions de l'atelier mené avec @aureliebaton : 

- De nos discussions avec différents utilisateurs, il est établi que chacun utilise des modèles d'arrêtés (certains sont même mis à disposition par les préfectures et conseils départementaux à l'attention des communes).
- L'objectif serait donc de permettre aux utilisateurs de gérer un ensemble de modèles de visas utilisables par tous les membres de l'organisation
- Un modèle de visas est en fait un ensemble de visas pré rédigé que l'utilisateur pourrait appeler lors de la création d'un nouvel arrêté dans DiaLog. Par exemple une organisation pourrait avoir un modèle "Arrêté pour travaux de voirie", l'utilisateur pourrait choisir ce modèle au moment de créer son nouvel arrêté pour que l'export Word fasse figurer les visas en en-tête.
- Ceci suppose de disposer d'une interface pour gérer ces modèles, ceux-ci étant propres à une organisation, cela pose la question de qui est chargé de gérer ces modèles ? Est-ce que tous les membres peuvent le faire ? Sinon qui peut et quel rôle cela définit il ?

En premières conclusion il apparaît donc possible de travailler sur ce que serait cette interface de gestion des modèles, et sur l'intégration dans le formulaire d'écriture d'un arrêté de la possibilité d'ajout des visas.

De manière plus large, l'évolution de DiaLog pour permettre de générer des arrêtés complets pousse à réfléchir à un certain nombre d'autres sujets : 

1° La possibilité d'un rôle de super user, chargé d'administrer notamment les modèles d'arrêtés de l'organisation mais peut être d'autres éléments du modèle : uploader un logo qui figure sur l'arrêté ? Modifier le nom de l'organisation ? etc.
2° Si nous optons pour un super user, on peut envisager des processus de validation pour la publication d'un arrêté. Si le super user est le maire, il peut valider la publication d'arrêtés dans DiaLog proposés par ses services (exemple un peu caricatural).
3° De la même manière que les visas, il est souhaitable de permettre à l'utilisateur de rédiger les motifs de l'arrêté, qui sont les "Considérant"... Ces éléments étant propres à chaque arrêtés, il ne peut y avoir de modèle préconstruit (à priori), et l'interface de rédaction des motifs devrait donc être intégrée au formulaire de rédaction d'un nouvel arrêté.
4° Si nous travaillons sur ces fonctionnalités, une refonte de l'export word permettra de proposer quelques évolutions esthétiques pour soigner le rendu : Utilisation de la police d'écriture Marianne, logo, présentation globale du document...

**Comment by aureliebaton** [comment]
Notes issues du pad du 2024-06-17 - Point UX - exploration Visas + Motifs

Des axes d’amélioration du produit visant l’impact “collectivités” et glanés au fil

**Visas et Motifs**

Objectif : Offrir la possibilité d’entrer dans DiaLog des templates d’annexes (Vu le…) et permettre d’entrer les motifs de l’arrêté (Considérant…)

Idée :
* L’utilisateur dispose d’une interface pour gérer des templates d’annexes. Un template consiste en une liste d’annexes conformes à la syntaxe “Vu…”. - A la création d’un nouvel arrêté l’utilisateur peut choisir d’affecter un template d’annexes à l’arrêté pour qu’elles apparaissent en en-tête de l’arrêté dans l’export Word
*  Optionnel : On laisse la possibilité d’ajouter une ou des annexes supplémentaires au cas où
* De la même manière on offre la possibilité d’écrire les motifs conformément à la syntaxe “Considérant…”
* A la différence des annexes, les motifs sont propres à un arrêté et ne peuvent pas être stockés dans des templates.

L’export word doit faire usage de ces données.
