### ISSUE TITLE
Inversion localisations et restrictions

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#577]
## Contexte

Suite à l'atelier du 14/12/2023, une exploration a été réalisée au sujet des restrictions auxquelles sont rattachées plusieurs localisations, à voir en détails dans #522.

Aujourd'hui DiaLog permet de renseigner plusieurs Restrictions sur une Localisation.

Des exemples d'arrêtés ont été trouvés, notamment ceux qui portent sur des zones, montrant la nécessité de pouvoir renseigner plusieurs Localisations sur une Restriction (voir section "Exemple").

Il semble que le cas majoritaire serait de déclarer d'abord la restriction puis de lui lier une ou plusieurs localisations plutôt que l'inverse. Le cas des réglementations par zones est un exemple de ce que cette inversion permettrait.

![Image](https://github.com/MTES-MCT/dialog/assets/65396841/fd8826d3-8e52-4c79-919b-25cb2e5dcf84)

Afin de couvrir le cas minoritaire où plusieurs restrictions sont rattachées à une unique Localisation, il sera nécessaire d'ajouter la possibilité de dupliquer le bloc Restriction + Localisations, que l'on nomme "Mesure".

![Image](https://github.com/MTES-MCT/dialog/assets/65396841/3a2e188b-b9a4-443d-a450-0ca116f6992f)

Par ailleurs ce ticket est l'occasion de réaliser quelques changements d'interface, notamment baptiser "Dispositif" l'ensemble des mesures qui figurent dans un arrêté, section qui se nomme aujourd'hui "Localisations" et qui n'aura donc plus lieu d'être.

![Image](https://github.com/MTES-MCT/dialog/assets/65396841/bbc241d0-5309-4263-b02e-8aa36c408a31)

## Exemple

Un exemple de restrictions qui est valable sur une zone, une zone étant ici comprise comme un ensemble de Localisations, cela justifie d'inverser le fonctionnement actuel en Localisation>Restrictions vers Restriction>Localisation.

![Image](https://github.com/MTES-MCT/dialog/assets/65396841/ac665f67-46f3-4ab0-9934-dbf700862db6)

Par ailleurs plusieurs exemples d'arrêtés renseignés dans DiaLog mettent en évidence la difficulté que peut représenter l'écriture d'un arrêté qui possède plusieurs localisations pour une même restriction : 

- Un arrêté temporaire de Toulouse au sujet d'une course à pieds, 63 localisations utilisent la même restriction :

https://dialog.beta.gouv.fr/regulations/69618570-ef1b-4e47-9532-80fe57a1c597

- Un arrêté obtenu à partir d'Eudonet où l'on voit apparaître plusieurs fois la localisation "Rue du Faubourg Saint-Jacques", seuls les numéros changent mais le bloc de la mesure possède dans ce cas le même nom à chaque fois, pouvant induire des incompréhensions.

https://dialog.beta.gouv.fr/regulations/018b6c90-02a7-75a7-a6c6-ceb7ccca9cbd

L'inversion proposée permettrait à priori d'apporter des solutions à ce problème car un utilisateur rassemblera plus intuitivement dans un seul bloc mesure toutes les rues qui possèdent la même restriction, par exemple toutes les rues dont la circulation est interdite. Si le bloc mesure porte le nom de la Restriction et pas de la Localisation, le résultat devrait dont être plus lisible dans l'interface.

## Implémentation

Afin de faire aboutir cet epic en parallèle d'autres tâches sur lesquelles il y aurait des répercussions, on décide 1) de faire évoluer le modèle de données en faisant transitoirement cohabiter en production le modèle de données actuel et le nouveau, puis 2) de migrer et porter les fonctionnalités de l'application et ses données actuellement en production vers ce nouveau modèle, sans faire évoluer l'UI, avant 3) d'implémenter la nouvelle UI souhaitée.

* [x] Faire cohabiter les 2 modèles en production
  * [x] #594
  * [x] #599 
  * [x] #600 
* [x] Une fois le nouveau modèle implémenté, migrer les données dessus :
  * [x] Base de données
  * [x] Export Datex II #608 
  * [x] Export CIFS
  * [x] Export DOCX
  * [x] Tests
* [x] #597
* [x] Vérifier que l'application fonctionne comme auparavant (UI iso et sans régressions)
  * [x] [Page qui permet de naviguer dans la liste des arrêtés](https://dialog.beta.gouv.fr/regulations)
  * [x] Duplication d'un arrêté (bouton "Dupliquer" sur la page d'un arrêté publié)
* [x] Supprimer anciennes données et code de l'ancienne UI
* [x] #642

Cet epic a vocation a rassembler et suivre les différentes tâches liées à son implémentation. Cette liste de tâche peut être affinée au fur et faire l'objet de PR voire de nouveaux tickets dédiés (choix laissé à la discrétion des personnes qui travaillent dessus).

## Critères d'acceptation

* (Must have) Lors de l'édition d'un arrêté, l'utilisateur commence en renseignant la restriction puis lui affecte une ou plusieurs localisations
* (Must have) L'export DATEX est aligné avec le nouveau modèle de données
* (Must have) L'export word est aligné avec le nouveau modèle de données
* (Must have) L'import de données Eudonet (scripts d'intégration) est compatible avec le nouveau modèle de données

Hors périmètre :
* En dehors de l'UI d'édition (et validation) d'arrêté qui fera l'objet d'évolution détaillées dans un ticket dédié (voir liste ci-dessus), le reste de l'interface reste pour l'instant inchangée ("iso"), notamment [la page qui permet de naviguer dans la liste des arrêtés](https://dialog.beta.gouv.fr/regulations), et doit donc être portée sans régressions
* Faciliter la duplication d'une restriction
* Valider qu'une restriction n'est pas en double (mêmes définition et localisations)

**Comment by mmarchois** [comment]
Plan d'action :
 
- Création d'une nouvelle table `LocationNew` et l'associer à `Measure`
- Migration LocationNew
-  Dans le back, à chaque création/modification de Location, on créer aussi le LocationNew

**Comment by florimondmanca** [comment]
@MathieuFV 

> (Must have) Le nom de section "Localisations" dans la page d'édition/affichage d'un arrêté devient "Dispositif"

Je suis d'accord avec @johanricher que le vocable "Dispositif" peut être un sujet à part, car on pourrait changer dès aujourd'hui "Localisations" en "Dispositif" dans l'UI, ou à l'inverse traiter ce ticket en écrivant "Mesures" à la place de "Localisations"

**Comment by aureliebaton** [comment]
Les maquettes en exploration sont disponibles ici : https://www.figma.com/file/YuT6Uh4wxe90U8LaPLlDzO/Dialog?type=design&node-id=4321%3A15491&mode=design&t=9DTCTuLtZDnvOszw-1

**Comment by florimondmanca** [comment]
Soutien supplémentaire à cette approche les données BAC-IDF sont structurées en "Une restriction contient une ou plusieurs localisations"... :+1:

**Comment by johanricher** [comment]
J'ai mis à jour les parties Implémentation et Critères d'acceptation du ticket. @aureliebaton @florimondmanca @MathieuFV @mmarchois @Lealefoulon je vous laisse relire, compléter et/ou corriger afin qu'on puisse considérer ce ticket comme "prêt à développer".

**Comment by aureliebaton** [comment]
@johanricher @mmarchois  Ca me semble bien correspondre à ce qu'on s'est dit. 
Mais je me demande s'il manque pas quelque chose sur le bloc "résumé" (une fois le formulaire vaildé), j'imagine qu'il y a un impact notamment sur l'ordre des infos (indépendamment des changement de visualisation de la UI)

**Comment by florimondmanca** [comment]
Suite du point du jour

* Séparer `GetRegulationOrderRecordSummaryQuery` en deux : d'une part `GetGeneralInfoQuery`, d'autre part `GetRegulationLocationsQuery`, qui renvoie des `DetailLocationView`
* DATEX2 : en principe
* Envisager d'implémenter l'UI d'affichage et le nouvel Export Word caché derrière un feature flag (même principe que #571), pour réduire au maximum la "tentacularité"

**Comment by mmarchois** [comment]
Après vérification, l'export DATEX2 est déjà passé sous le nouveau modèle.
