### ISSUE TITLE
Conversion des localisations en tronçons

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#793]
## Problème

Actuellement les localisations sont calculées à partir de la table `voie_nommee`

Waze / CIFS a besoin de localisations correspondant à des "segments" entiers, c'est-à-dire des tronçons de route situées entre deux noeuds du réseau (intersections, etc)

Cette limitation a du sens de leur point de vue de calculateur d'itinéraire qui raisonne sur un réseau routier

On a donc deux problèmes

* La plupart de nos localisations ne peuvent pas être intégrées par Waze dès lors qu'elles ont + de 1 tronçon, car un incident Waze ne peut concerner qu'1 seul tronçon
* DiaLog permet de créer des localisations dont les extrémités tombent à l'intérieur d'un tronçon, créant des "tronçons partiels" que Waze ne saurait pas intérpreter, car il ne prend que des tronçons "entiers"

## Solution envisagée

La table `troncon_de_route` de la BD TOPO nous permet de nous rapprocher des "segments" Waze (enfin `troncon_de_route` est plus riche que les "segments" Waze, car Waze ne connaît pas toutes les allées chemins et autres petites voies)

=> Convertir nos localisations en assemblage de `troncons_de_route` plutôt qu'en section de `voie_nommee`, afin d'exporter 1 incident par tronçon à Waze
Ensuite, en cas de section, les tronçons d'extrémités seraient partiels donc toujours pas intégrables dans Waze :

```
   A              B
|--[---|---|---|--]---|
   [ localisation ]

|---| = tronçon
```

=> "Recaler" les tronçons partiels en tronçons complets ? Solution technique à clarifier. Calcul à la volée lors de l'export CIFS ? Stockage d'une géométrie dérivée ? Nécessite une requête à la BD TOPO, qui nécessiterait de pouvoir retrouver l'ID du tronçon ?

## Implémentation

* [x] Voie nommée entière #773
* [x] Section de voie nommée #795 
* [x] Section de route départementale #795

## Contexte supplémentaire

* Facilite #713 (mini-calcul d'itinéraire au niveau tronçon)
* Contribue à #716 (localisations par sur des segments)
* Débloquerait #691 (les `troncon_de_route` contiennent la donnée `sens_de_circulation`)

**Comment by florimondmanca** [comment]
A priori on peut clore ce ticket comme résolu ? cc @mmarchois @johanricher

**Comment by johanricher** [comment]
Oui ça a l'air de fonctionner du tonnerre !
