### ISSUE TITLE
Permissions des utilisateurs

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#86]
Refs #87

## Définition du problème

DiaLog sera utilisé par différentes personnes. Il faut définir qui.

Ensuite, il faut définir quels sont les droits accordés à quel type d'utilisateur.

### Rôles utilisateurs

* Rôle utilisateur standard
  * Peut VOIR les réglementations de son organisation uniquement
    * [x] La liste affiche seulement les réglementations de son organisation https://github.com/MTES-MCT/dialog/pull/144
    * [x] Une réglementation publiée est visible seulement si l'utilisateur fait partie de la même organisation
  * Peut CHANGER (ajouter, modifier, supprimer) uniquement des réglementations dans son organisation
    * [x] Le formulaire d'une réglementation est accessible seulement si l'utilisateur fait partie de la même organisation
    * [x] Les endpoints de modification sont protégés selon cette même règle
* Rôle super-admin (pour l'équipe technique)
  * Peut VOIR toutes les réglementations
  * Peut CHANGER toutes les réglementations

### Organisations

Règle : un utilisateur peut gérer la réglementation liée à son organisation

Une organisation est identifiée par son SIRET

### Permissions géographiques

Règle : la localisation d'une réglementation doit être située dans la zone correspondant à son organisation (associée à un (multi)polygône)

Exemple : en tant qu'agent de la mairie de Savenay, je ne peux pas créer une réglementation portant sur une rue à Saint-Nazaire, ni modifier une réglementation existante pour la faire s'appliquer à quelque part en dehors de Savenay.

Exemple : en tant qu'agent du département de la Loire, je peux créer une réglementation portant sur n'importe où dans le département, donc y compris à Savenay.

Limites :

* Certaines routes peuvent traverser une entité administrative mais ne pas être gérées par elle. Par exemple, une route départementale qui traverse une commune mais sur laquelle c'est le département qui gère la réglementation temporaire.

**Comment by mmarchois** [comment]
Je clos cette issue car c'est le fonctionnement actuel.
