### ISSUE TITLE
EPIC 1 - Connexion et accès

### ISSUE THREAD

**Issue by florimondmanca** [MTES-MCT/dialog#87]
## Résumé

_TODO_

## Critères d'acceptation

* [x] L'accès à DiaLog est protégé
    * Identifiants partagés : #54
* [x] DiaLog permet à des utilisateurs différents de se connecter de façon sécurisée
  * #135 
  * Utilisateurs séparés : #137 
* [x] Les utilisateurs ont accès aux fonctionnalités appropriées
   * #86
