### ISSUE TITLE
Rôles utilisateurs

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#871]
## User story

Les utilisateurs DiaLog ont fait remonter deux besoins importants : 

1° Rendre possible de gérer les visas au travers de modèles qui pourront être associés aux arrêtés.
2° Rendre possible de limiter le rôle d'un utilisateur à la rédaction d'arrêtés dont la publication est modérée par un autre utilisateur.

Ces deux besoins impliquent de pouvoir gérer les modèles de visas et les rôles utilisateurs à l'échelle d'une organisation, ce qui apportera aussi des solutions aux problèmes soulevés dans #183 et #683 (qui seront fermés à l'occasion de l'ouverture de ce ticket).

**En prérequis, on examinera la compatibilité des critères d'acceptation avec une implémentation du SSO MonComptePro.**

## Critères d'acceptation

- [x] _(Must have)_ Les utilisateurs DiaLog ont un rôle parmi : ADMIN (super admin), ORGA_ADMIN (administrateur de l'organisation), ORGA_PUBLISHER (rédacteur et publicateur de l'organisation), ORGA_CONTRIBUTOR (rédacteur de l'organisation).
- [x] _(Must have)_ L'administrateur de l'organisation peut ouvrir des comptes contributeur ou publieur à d'autres personnes de son organisation et gérer ces rôles.
- [ ]  _(Must have)_ L'administrateur de l'organisation peut gérer les modèles de visas qui sont utilisables dans les arrêtés rédigés par les contributeurs. Voir #557 
- [ ]  _(Must have)_ L'administrateur de l'organisation peut gérer des éléments de personnalisation des arrêtés word générés à partir de DiaLog (logo, signature, autre ? => A explorer).
- [x]  _(Must have)_ L'administrateur de l'organisation peut rédiger et publier des arrêtés sur DiaLog
- [x]  _(Must have)_ Le publieur ne peut que rédiger et publier des arrêtés sur DiaLog
- [x]  _(Must have)_ Le rédacteur ne peut que rédiger des projets d'arrêtés sur DiaLog

**Comment by MathieuFV** [comment]
Je remets le contenu du brainstorming du 09/07 : 

Mathieu M et Mathieu F

**Regarder la compatibilité de moncomptepro avec notre gestion des rôles**

- Gestion des droits
- Règles métier
- Liste des différents rôles :
-- ROLE_ADMIN (Mathieu F)
-- ROLE_ORGA_ADMIN (peut administrer l'orga et publier des arrêtés) => premier connecté dans l'orga
-- ROLE_ORGA_PUBLISHER (peut uniquement publier)
-- ROLE_ORGA_CONTRIBUTOR (peut uniquement créer / modifier un arrêté)

=> Administrateur de l'organisation : 

- Manager les rôles des autres utilisateurs de son organisation : 
-- Créer / modifier / supprimer des utilisateurs (ne peut créer que des contributeurs/publieurs)
-- Gérer les modèles de visas utilisables dans les arrêtés
-- Ajouter un logo, une signature, différents éléments de personnalisation de l'export word...
-- Approuver la publication des arrêtés OU donner le droit à un contributeur de publier

- Le super admin peut gérer les admins des orgas

- Un utilisateur peut-il avoir des rôles différents dans des organisations différentes ?

=> Workflow inscription : 

Cas 1 : l'organisation n'existe pas dans DiaLog : Je demande l'ouverture d'un compte et la création de l'organisation. Le super admin approuve le compte et la création de l'orga. Je suis admin de l'orga

Cas 2 : Mon organisation existe déjà dans DiaLog

2 choix : 

Choix 1 : Je dois être ajouté par mon administrateur via l'UI d'administration de l'organisation.

Choix 2 : Je m'inscris via le formulaire MAIS je suis automatiquement dans le rôle de contributeur. Mon inscription est validée par l'administrateur de l'organisation.

(Améliorer le formulaire d'inscription : choix de l'organisation dans une liste ? via le SIRET uniquement ?)

Pour les utilisateurs existants : Comment attribuer le rôle admin pour les organisations qui ont plusieurs utilisateurs => Tout le monde est contributeur et le super admin donnera les droits d'amin au cas par cas.

UI (à confirmer avec Aurélie) : Faire apparaître le nom d'utilisateur + menu déroulant pour options (gestion du compte et gestion de l'orga pour l'admin)

=> Voir MonComptePro ?

DSFR : https://www.systeme-de-design.gouv.fr/composants-et-modeles/composants-beta/en-tete-connecte

=> Nouveau ticket + fermer les 183 et 683 obsolètes
