### ISSUE TITLE
Refonte de l'export Word

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#914]
## User story

L'ajout des fonctionnalités de gestion de l'organisation par leur administrateur (voir #871) ouvre des possibilités de personnalisation plus poussées pour l'export Word. Il est proposé une refonte de l'export Word pour inclure ces divers éléments de personnalisation.

## Critères d'acceptation

- [ ] _(Must have)_ Le logo de l'organisation est inclus dans l'export Word, dans un emplacement dédié
- [ ] _(Must have)_ L'adresse de l'établissement émetteur est inclus dans l'export Word
- [ ] _(Must have)_ L'intitulé du signataire figure sous la description de l'arrêté dans l'export Word
- [ ] _(Must have)_ La signature de l'arrêté dans l'export Word peut être personnalisée avec la ville (suivant la mention "Fait à") et la désignation du signataire de l'arrêté
- [ ] _(Must have)_ L'ensemble de ces éléments de personnalisation peuvent être modifiés par l'administrateur de l'organisation dans l'espace d'administration
- [ ] _(Must have)_ En l'absence de précisions de l'administrateur de l'organisation, l'export word fera figurer des placeholders en lieu et place des éléments sus cités.

## Contexte supplémentaire

Voir l'exemple d'export en commentaire pour référence.

**Comment by MathieuFV** [comment]
Voici l'exemple d'export que j'ai créé pour référence : 

[Export DiaLog v2.docx](https://github.com/user-attachments/files/16541972/Export.DiaLog.v2.docx)
