### ISSUE TITLE
Réglementation de stationnement

### ISSUE THREAD

**Issue by MathieuFV** [MTES-MCT/dialog#984]
## User story

Pour disposer d'une vision complète de leur réglementation de voirie dans DiaLog, et notamment pouvoir améliorer le fonctionnement de la logistique sur leur territoire, les utilisateurs de DiaLog doivent pouvoir numériser leur réglementation de stationnement.

Les données renseignées par les utilisateurs et stockées dans la base devront permettre des réutilisations par des calculateurs d'itinéraires et des outils métiers de cartographie, et comporter à la fois des informations sur l'emplacement & les dimensions des aires de stationnement, tout en leur associant leurs règles d'utilisation (aire de livraison, stationnement réservé véhicules électrique, vélos / 2RM, horaires, etc.).

## Critères d'acceptation

- [ ] _(Must have)_ Les utilisateurs de DiaLog peuvent saisir des réglementations de stationnement dans DiaLog
- [ ] _(Must have)_ Les données de réglementation de stationnement sont exposées sur les API afin d'être réutilisables par les calculateurs d'itinéraires
- [ ] _(Must have)_ Les données saisies s'exportent dans le word à l'article 2
- [ ] _(Nice to have)_ examiner dans les données importées depuis les API externes (Sogelink) comment ces données peuvent être ajoutées à DiaLog

## Design

A explorer : analyser des arrêtés de stationnement et examiner les adaptations possibles du formulaire actuel pour prendre en charge ces documents.

Produire une maquette sur la base de cette analyse comme point de départ.
